/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// AddOffersToArchiveErrorType : Причина, по которой товар не удалось поместить в архив:  * `OFFER_HAS_STOCKS` — товар хранится на складе Маркета.

/// Причина, по которой товар не удалось поместить в архив:  * `OFFER_HAS_STOCKS` — товар хранится на складе Маркета.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddOffersToArchiveErrorType {
    #[serde(rename = "OFFER_HAS_STOCKS")]
    OfferHasStocks,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl ToString for AddOffersToArchiveErrorType {
    fn to_string(&self) -> String {
        match self {
            Self::OfferHasStocks => String::from("OFFER_HAS_STOCKS"),
            Self::Unknown => String::from("UNKNOWN"),
        }
    }
}

impl Default for AddOffersToArchiveErrorType {
    fn default() -> AddOffersToArchiveErrorType {
        Self::OfferHasStocks
    }
}
