/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};
use std::fmt::Display;

/// AgeUnitType : Единицы измерения возраста:  * `YEAR` — год. * `MONTH` — месяц.

/// Единицы измерения возраста:  * `YEAR` — год. * `MONTH` — месяц.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgeUnitType {
    #[serde(rename = "YEAR")]
    Year,
    #[serde(rename = "MONTH")]
    Month,
}

impl Display for AgeUnitType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str = match self {
            Self::Year => String::from("YEAR"),
            Self::Month => String::from("MONTH"),
        };
        write!(f, "{}", str)
    }
}

impl Default for AgeUnitType {
    fn default() -> AgeUnitType {
        Self::Year
    }
}
