/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ApiLockedErrorResponse : Ресурс из запроса заблокирован от применения к нему указанного метода.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiLockedErrorResponse {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::ApiResponseStatusType>,
    /// Список ошибок.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::ApiErrorDto>>,
}

impl ApiLockedErrorResponse {
    /// Ресурс из запроса заблокирован от применения к нему указанного метода.
    pub fn new() -> ApiLockedErrorResponse {
        ApiLockedErrorResponse {
            status: None,
            errors: None,
        }
    }
}
