/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// BidRecommendationItemDto : Рекомендованная ставка и возможная доля показов.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BidRecommendationItemDto {
    /// Значение ставки.
    #[serde(rename = "bid")]
    pub bid: i32,
    /// Доля показов.
    #[serde(rename = "showPercent")]
    pub show_percent: i64,
}

impl BidRecommendationItemDto {
    /// Рекомендованная ставка и возможная доля показов.
    pub fn new(bid: i32, show_percent: i64) -> BidRecommendationItemDto {
        BidRecommendationItemDto { bid, show_percent }
    }
}
