/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// CalculateTariffsOfferDto : Параметры товара, для которого нужно рассчитать стоимость услуг.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CalculateTariffsOfferDto {
    /// Идентификатор категории товара на Маркете.  Для расчета стоимости услуг необходимо указать идентификатор листовой категории товара — той, которая не имеет дочерних категорий.  Чтобы узнать идентификатор категории, к которой относится товар, воспользуйтесь запросом [POST categories/tree](../../reference/categories/getCategoriesTree.md).
    #[serde(rename = "categoryId")]
    pub category_id: i64,
    /// Цена на товар в рублях.
    #[serde(rename = "price")]
    pub price: f32,
    /// Длина товара в сантиметрах.
    #[serde(rename = "length")]
    pub length: f32,
    /// Ширина товара в сантиметрах.
    #[serde(rename = "width")]
    pub width: f32,
    /// Высота товара в сантиметрах.
    #[serde(rename = "height")]
    pub height: f32,
    /// Вес товара в килограммах.
    #[serde(rename = "weight")]
    pub weight: f32,
    /// Квант продажи — количество единиц товара в одном товарном предложении.
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i32>,
}

impl CalculateTariffsOfferDto {
    /// Параметры товара, для которого нужно рассчитать стоимость услуг.
    pub fn new(
        category_id: i64,
        price: f32,
        length: f32,
        width: f32,
        height: f32,
        weight: f32,
    ) -> CalculateTariffsOfferDto {
        CalculateTariffsOfferDto {
            category_id,
            price,
            length,
            width,
            height,
            weight,
            quantity: None,
        }
    }
}
