/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// CampaignSettingsLocalRegionDto : Информация о своем регионе магазина.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CampaignSettingsLocalRegionDto {
    /// Идентификатор региона.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Название региона.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::RegionType>,
    #[serde(
        rename = "deliveryOptionsSource",
        skip_serializing_if = "Option::is_none"
    )]
    pub delivery_options_source: Option<crate::models::CampaignSettingsScheduleSourceType>,
    #[serde(rename = "delivery", skip_serializing_if = "Option::is_none")]
    pub delivery: Option<Box<crate::models::CampaignSettingsDeliveryDto>>,
}

impl CampaignSettingsLocalRegionDto {
    /// Информация о своем регионе магазина.
    pub fn new() -> CampaignSettingsLocalRegionDto {
        CampaignSettingsLocalRegionDto {
            id: None,
            name: None,
            r#type: None,
            delivery_options_source: None,
            delivery: None,
        }
    }
}
