/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// CampaignQualityRatingDto : Информация об индексе качества магазина.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CampaignQualityRatingDto {
    /// Идентификатор магазина.
    #[serde(rename = "campaignId")]
    pub campaign_id: i64,
    /// Список значений индекса качества.
    #[serde(rename = "ratings")]
    pub ratings: Vec<crate::models::QualityRatingDto>,
}

impl CampaignQualityRatingDto {
    /// Информация об индексе качества магазина.
    pub fn new(
        campaign_id: i64,
        ratings: Vec<crate::models::QualityRatingDto>,
    ) -> CampaignQualityRatingDto {
        CampaignQualityRatingDto {
            campaign_id,
            ratings,
        }
    }
}
