/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ChatMessagePayloadDto : Информация о приложенных к сообщению файлах.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ChatMessagePayloadDto {
    /// Имя файла.
    #[serde(rename = "name")]
    pub name: String,
    /// Ссылка для скачивания файла.
    #[serde(rename = "url")]
    pub url: String,
    /// Размер файла в байтах.
    #[serde(rename = "size")]
    pub size: i32,
}

impl ChatMessagePayloadDto {
    /// Информация о приложенных к сообщению файлах.
    pub fn new(name: String, url: String, size: i32) -> ChatMessagePayloadDto {
        ChatMessagePayloadDto { name, url, size }
    }
}
