/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// ConfirmPricesRequest : Запрос на подтверждение цены.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConfirmPricesRequest {
    /// Идентификаторы товаров, у которых подтверждается цена.
    #[serde(rename = "offerIds")]
    pub offer_ids: Vec<String>,
}

impl ConfirmPricesRequest {
    /// Запрос на подтверждение цены.
    pub fn new(offer_ids: Vec<String>) -> ConfirmPricesRequest {
        ConfirmPricesRequest { offer_ids }
    }
}
