/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// DeleteOffersFromArchiveDto : Товары, которые не удалось восстановить из архива.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteOffersFromArchiveDto {
    /// Список товаров, которые не удалось восстановить из архива.
    #[serde(
        rename = "notUnarchivedOfferIds",
        skip_serializing_if = "Option::is_none"
    )]
    pub not_unarchived_offer_ids: Option<Vec<String>>,
}

impl DeleteOffersFromArchiveDto {
    /// Товары, которые не удалось восстановить из архива.
    pub fn new() -> DeleteOffersFromArchiveDto {
        DeleteOffersFromArchiveDto {
            not_unarchived_offer_ids: None,
        }
    }
}
