/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// DeleteCampaignOffersRequest : Фильтрации удаляемых товаров по offerIds.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeleteCampaignOffersRequest {
    /// Идентификаторы товаров в каталоге.
    #[serde(rename = "offerIds")]
    pub offer_ids: Vec<String>,
}

impl DeleteCampaignOffersRequest {
    /// Фильтрации удаляемых товаров по offerIds.
    pub fn new(offer_ids: Vec<String>) -> DeleteCampaignOffersRequest {
        DeleteCampaignOffersRequest { offer_ids }
    }
}
