/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EnrichedMappingsOfferDtoAllOf {
    /// Идентификатор категории для рекомендованной карточки товара на Маркете.  Возвращается только вместе с параметром ##marketSku##.
    #[serde(rename = "marketCategoryId", skip_serializing_if = "Option::is_none")]
    pub market_category_id: Option<i64>,
    /// Название категории для рекомендованной карточки товара на Маркете.  Может отсутствовать в ответе.
    #[serde(rename = "marketCategoryName", skip_serializing_if = "Option::is_none")]
    pub market_category_name: Option<String>,
    /// Идентификатор модели для рекомендованной карточки товара на Маркете.  Может отсутствовать в ответе.
    #[serde(rename = "marketModelId", skip_serializing_if = "Option::is_none")]
    pub market_model_id: Option<i64>,
    /// Название модели для рекомендованной карточки товара на Маркете.  Возвращается только вместе с параметром ##marketSku##.
    #[serde(rename = "marketModelName", skip_serializing_if = "Option::is_none")]
    pub market_model_name: Option<String>,
    /// SKU на Маркете.
    #[serde(rename = "marketSku", skip_serializing_if = "Option::is_none")]
    pub market_sku: Option<i64>,
    /// Название товара с рекомендованной карточки на Маркете.  Может отсутствовать в ответе.
    #[serde(rename = "marketSkuName", skip_serializing_if = "Option::is_none")]
    pub market_sku_name: Option<String>,
}

impl EnrichedMappingsOfferDtoAllOf {
    pub fn new() -> EnrichedMappingsOfferDtoAllOf {
        EnrichedMappingsOfferDtoAllOf {
            market_category_id: None,
            market_category_name: None,
            market_model_id: None,
            market_model_name: None,
            market_sku: None,
            market_sku_name: None,
        }
    }
}
