/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// EnrichedOrderBoxLayoutDto : Информация о коробке.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EnrichedOrderBoxLayoutDto {
    /// Список товаров в коробке.  Если в коробке едет часть большого товара, в списке может быть только один пункт.
    #[serde(rename = "items")]
    pub items: Vec<crate::models::OrderBoxLayoutItemDto>,
    /// Идентификатор коробки.
    #[serde(rename = "boxId", skip_serializing_if = "Option::is_none")]
    pub box_id: Option<i64>,
}

impl EnrichedOrderBoxLayoutDto {
    /// Информация о коробке.
    pub fn new(items: Vec<crate::models::OrderBoxLayoutItemDto>) -> EnrichedOrderBoxLayoutDto {
        EnrichedOrderBoxLayoutDto {
            items,
            box_id: None,
        }
    }
}
