/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// FeedDownloadDto : Информация о последней загрузке прайс-листа.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FeedDownloadDto {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::FeedStatusType>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<crate::models::FeedDownloadErrorDto>>,
}

impl FeedDownloadDto {
    /// Информация о последней загрузке прайс-листа.
    pub fn new() -> FeedDownloadDto {
        FeedDownloadDto {
            status: None,
            error: None,
        }
    }
}
