/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// FeedbackDeliveryType : Способ покупки, указанный в отзыве:  * `DELIVERY` — доставка. * `PICKUP` — самовывоз. * `INSTORE` — в магазине.

/// Способ покупки, указанный в отзыве:  * `DELIVERY` — доставка. * `PICKUP` — самовывоз. * `INSTORE` — в магазине.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FeedbackDeliveryType {
    #[serde(rename = "DELIVERY")]
    Delivery,
    #[serde(rename = "PICKUP")]
    Pickup,
    #[serde(rename = "INSTORE")]
    Instore,
}

impl ToString for FeedbackDeliveryType {
    fn to_string(&self) -> String {
        match self {
            Self::Delivery => String::from("DELIVERY"),
            Self::Pickup => String::from("PICKUP"),
            Self::Instore => String::from("INSTORE"),
        }
    }
}

impl Default for FeedbackDeliveryType {
    fn default() -> FeedbackDeliveryType {
        Self::Delivery
    }
}
