/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ForwardScrollingPagerDto : Ссылка на следующую страницу.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ForwardScrollingPagerDto {
    /// Идентификатор следующей страницы результатов.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ForwardScrollingPagerDto {
    /// Ссылка на следующую страницу.
    pub fn new() -> ForwardScrollingPagerDto {
        ForwardScrollingPagerDto {
            next_page_token: None,
        }
    }
}
