/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FullOutletDtoAllOf {
    /// Идентификатор точки продаж, присвоенный Маркетом.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::OutletStatusType>,
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<Box<crate::models::RegionDto>>,
    /// Идентификатор точки продаж, заданный магазином.
    #[serde(rename = "shopOutletId", skip_serializing_if = "Option::is_none")]
    pub shop_outlet_id: Option<String>,
    /// Рабочее время.
    #[serde(rename = "workingTime", skip_serializing_if = "Option::is_none")]
    pub working_time: Option<String>,
    /// Статус модерации.
    #[serde(rename = "moderationReason", skip_serializing_if = "Option::is_none")]
    pub moderation_reason: Option<String>,
}

impl FullOutletDtoAllOf {
    pub fn new() -> FullOutletDtoAllOf {
        FullOutletDtoAllOf {
            id: None,
            status: None,
            region: None,
            shop_outlet_id: None,
            working_time: None,
            moderation_reason: None,
        }
    }
}
