/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// GenerateGoodsRealizationReportRequest : Данные, необходимые для генерации отчета: идентификатор магазина и период, за который нужен отчет.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GenerateGoodsRealizationReportRequest {
    /// Идентификатор кампании.
    #[serde(rename = "campaignId")]
    pub campaign_id: i64,
    /// Год.
    #[serde(rename = "year")]
    pub year: i32,
    /// Номер месяца.
    #[serde(rename = "month")]
    pub month: i32,
}

impl GenerateGoodsRealizationReportRequest {
    /// Данные, необходимые для генерации отчета: идентификатор магазина и период, за который нужен отчет.
    pub fn new(campaign_id: i64, year: i32, month: i32) -> GenerateGoodsRealizationReportRequest {
        GenerateGoodsRealizationReportRequest {
            campaign_id,
            year,
            month,
        }
    }
}
