/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// GenerateUnitedMarketplaceServicesReportRequest : Данные, необходимые для генерации отчета: идентификатор магазина, период, за который нужен отчет, а также фильтры.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GenerateUnitedMarketplaceServicesReportRequest {
    /// Идентификатор бизнеса.
    #[serde(rename = "businessId")]
    pub business_id: i64,
    /// {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %}  Начало периода, включительно.
    #[serde(rename = "dateTimeFrom", skip_serializing_if = "Option::is_none")]
    pub date_time_from: Option<String>,
    /// {% note warning \"\" %}  Этот параметр устарел. Не используйте его.  {% endnote %}  Конец периода, включительно. Максимальный период — 1 год.
    #[serde(rename = "dateTimeTo", skip_serializing_if = "Option::is_none")]
    pub date_time_to: Option<String>,
    /// Начало периода, включительно.
    #[serde(rename = "dateFrom", skip_serializing_if = "Option::is_none")]
    pub date_from: Option<String>,
    /// Конец периода, включительно. Максимальный период — 1 год.
    #[serde(rename = "dateTo", skip_serializing_if = "Option::is_none")]
    pub date_to: Option<String>,
    /// Начальный год формирования акта.
    #[serde(rename = "yearFrom", skip_serializing_if = "Option::is_none")]
    pub year_from: Option<i32>,
    /// Начальный номер месяца формирования акта.
    #[serde(rename = "monthFrom", skip_serializing_if = "Option::is_none")]
    pub month_from: Option<i32>,
    /// Конечный год формирования акта.
    #[serde(rename = "yearTo", skip_serializing_if = "Option::is_none")]
    pub year_to: Option<i32>,
    /// Конечный номер месяца формирования акта.
    #[serde(rename = "monthTo", skip_serializing_if = "Option::is_none")]
    pub month_to: Option<i32>,
    /// Список моделей, которые нужны в отчете.
    #[serde(rename = "placementPrograms", skip_serializing_if = "Option::is_none")]
    pub placement_programs: Option<Vec<crate::models::PlacementType>>,
    /// Список ИНН, которые нужны в отчете.
    #[serde(rename = "inns", skip_serializing_if = "Option::is_none")]
    pub inns: Option<Vec<String>>,
    /// Список магазинов, которые нужны в отчете.
    #[serde(rename = "campaignIds", skip_serializing_if = "Option::is_none")]
    pub campaign_ids: Option<Vec<i64>>,
}

impl GenerateUnitedMarketplaceServicesReportRequest {
    /// Данные, необходимые для генерации отчета: идентификатор магазина, период, за который нужен отчет, а также фильтры.
    pub fn new(business_id: i64) -> GenerateUnitedMarketplaceServicesReportRequest {
        GenerateUnitedMarketplaceServicesReportRequest {
            business_id,
            date_time_from: None,
            date_time_to: None,
            date_from: None,
            date_to: None,
            year_from: None,
            month_from: None,
            year_to: None,
            month_to: None,
            placement_programs: None,
            inns: None,
            campaign_ids: None,
        }
    }
}
