/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// GenerateShelfsStatisticsRequest : Данные, необходимые для генерации отчета.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GenerateShelfsStatisticsRequest {
    /// Идентификатор бизнеса.
    #[serde(rename = "businessId")]
    pub business_id: i64,
    /// Начало периода, включительно.
    #[serde(rename = "dateFrom")]
    pub date_from: String,
    /// Конец периода, включительно.
    #[serde(rename = "dateTo")]
    pub date_to: String,
    #[serde(rename = "attributionType")]
    pub attribution_type: crate::models::ShelfsStatisticsAttributionType,
}

impl GenerateShelfsStatisticsRequest {
    /// Данные, необходимые для генерации отчета.
    pub fn new(
        business_id: i64,
        date_from: String,
        date_to: String,
        attribution_type: crate::models::ShelfsStatisticsAttributionType,
    ) -> GenerateShelfsStatisticsRequest {
        GenerateShelfsStatisticsRequest {
            business_id,
            date_from,
            date_to,
            attribution_type,
        }
    }
}
