/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// GetCampaignResponse : Информация о магазине к данным идентификатора кампании.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCampaignResponse {
    #[serde(rename = "campaign", skip_serializing_if = "Option::is_none")]
    pub campaign: Option<Box<crate::models::CampaignDto>>,
}

impl GetCampaignResponse {
    /// Информация о магазине к данным идентификатора кампании.
    pub fn new() -> GetCampaignResponse {
        GetCampaignResponse { campaign: None }
    }
}
