/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetGoodsStatsRequest : Запрос отчета по товарам.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetGoodsStatsRequest {
    /// Список ваших идентификаторов SKU.
    #[serde(rename = "shopSkus")]
    pub shop_skus: Vec<String>,
}

impl GetGoodsStatsRequest {
    /// Запрос отчета по товарам.
    pub fn new(shop_skus: Vec<String>) -> GetGoodsStatsRequest {
        GetGoodsStatsRequest { shop_skus }
    }
}
