/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCampaignOfferDtoAllOf {
    #[serde(rename = "basicPrice", skip_serializing_if = "Option::is_none")]
    pub basic_price: Option<Box<crate::models::GetPriceWithDiscountDto>>,
    #[serde(rename = "campaignPrice", skip_serializing_if = "Option::is_none")]
    pub campaign_price: Option<Box<crate::models::GetPriceWithVatDto>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::OfferCampaignStatusType>,
    /// Ошибки, препятствующие размещению товара на витрине.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::OfferErrorDto>>,
    /// Предупреждения, не препятствующие размещению товара на витрине.
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<crate::models::OfferErrorDto>>,
}

impl GetCampaignOfferDtoAllOf {
    pub fn new() -> GetCampaignOfferDtoAllOf {
        GetCampaignOfferDtoAllOf {
            basic_price: None,
            campaign_price: None,
            status: None,
            errors: None,
            warnings: None,
        }
    }
}
