/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// GetCampaignSettingsResponse : Ответ на запрос настроек магазина.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetCampaignSettingsResponse {
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<crate::models::CampaignSettingsDto>>,
}

impl GetCampaignSettingsResponse {
    /// Ответ на запрос настроек магазина.
    pub fn new() -> GetCampaignSettingsResponse {
        GetCampaignSettingsResponse { settings: None }
    }
}
