/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// GetOfferDto : Параметры товара.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOfferDto {
    /// Ваш SKU — идентификатор товара в вашей системе.  Разрешена любая последовательность длиной до 255 знаков.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * SKU товара нельзя менять — можно только удалить товар и добавить заново с новым SKU.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields)
    #[serde(rename = "offerId")]
    pub offer_id: String,
    /// Составляйте название по схеме: тип + бренд или производитель + модель + особенности, если есть (например, цвет, размер или вес) и количество в упаковке.  Не включайте в название условия продажи (например, «скидка», «бесплатная доставка» и т. д.), эмоциональные характеристики («хит», «супер» и т. д.). Не пишите слова большими буквами — кроме устоявшихся названий брендов и моделей.  Оптимальная длина — 50–60 символов, максимальная — 256.  [Рекомендации и правила](https://yandex.ru/support/marketplace/assortment/fields/title.html)
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Идентификатор категории на Маркете, к которой вы относите свой товар.  Если не указать `marketCategoryId`, то маркетная категория будет определена автоматически.  При изменении информации о товаре передавайте тот же идентификатор категории. Если вы укажете другой, категория товара не поменяется. Изменить ее можно только в кабинете продавца на Маркете.  Список категорий Маркета можно получить с помощью запроса  [POST categories/tree](../../reference/categories/getCategoriesTree.md).
    #[serde(rename = "marketCategoryId", skip_serializing_if = "Option::is_none")]
    pub market_category_id: Option<i64>,
    /// Категория товара в вашем магазине. Значение будет использовано для определения категории товара на Маркете в случае, если вы не передали категорию в параметре `marketCategoryId`.  Указывайте конкретные категории — например, набор ножей лучше отнести к категории **Столовые приборы**, а не просто **Посуда**.  Выбирайте категории, которые описывают товар, а не абстрактный признак — например, **Духи**, а не **Подарки**.  Значение будет использовано для определения категории товара на Маркете в случае, если вы не передали категорию в параметре `marketCategoryId`.
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Ссылки на изображения товара. Изображение по первой ссылке считается основным, остальные дополнительными.  **Требования к ссылкам**  * Ссылок может быть до 30. * Указывайте ссылку целиком, включая протокол http или https. * Максимальная длина — 512 символов. * Русские буквы в URL можно. * Можно использовать прямые ссылки на изображения и на Яндекс Диск. Ссылки на Яндекс Диске нужно копировать с помощью функции **Поделиться**. Относительные ссылки и ссылки на другие облачные хранилища — не работают.  ✅ `https://example-shop.ru/images/sku12345.jpg`  ✅ `https://yadi.sk/i/NaBoRsimVOLov`  ❌ `/images/sku12345.jpg`  ❌ `https://www.dropbox.com/s/818f/tovar.jpg`  Ссылки на изображение должны быть постоянными. Нельзя использовать динамические ссылки, меняющиеся от выгрузки к выгрузке.  Если нужно заменить изображение, выложите новое изображение по новой ссылке, а ссылку на старое удалите. Если просто заменить изображение по старой ссылке, оно не обновится.  [Требования к изображениям](https://yandex.ru/support/marketplace/assortment/fields/images.html)
    #[serde(rename = "pictures", skip_serializing_if = "Option::is_none")]
    pub pictures: Option<Vec<String>>,
    /// Ссылка (URL) на видео товара.  Максимальное количество ссылок — 6.  **Требования к ссылке**  * Указывайте ссылку целиком, включая протокол http или https. * Максимальная длина — 512 символов. * Русские буквы в URL можно. * Можно использовать прямые ссылки на видео и на Яндекс Диск. Ссылки на Яндекс Диске нужно копировать с помощью функции **Поделиться**. Относительные ссылки и ссылки на другие облачные хранилища — не работают.  ✅ `https://example-shop.ru/video/sku12345.avi`  ✅ `https://yadi.sk/i/NaBoRsimVOLov`  ❌ `/video/sku12345.avi`  ❌ `https://www.dropbox.com/s/818f/super-tovar.avi`  Ссылки на видео должны быть постоянными. Нельзя использовать динамические ссылки, меняющиеся от выгрузки к выгрузке.  Если нужно заменить видео, выложите новое видео по новой ссылке, а ссылку на старое удалите. Если просто заменить видео по старой ссылке, оно не обновится.  [Требования к видео](https://yandex.ru/support/marketplace/assortment/fields/video.html)
    #[serde(rename = "videos", skip_serializing_if = "Option::is_none")]
    pub videos: Option<Vec<String>>,
    /// Список инструкций по использованию товара.  Максимальное количество инструкций — 6.  Если вы передадите пустое поле `manuals`, загруженные ранее инструкции удалятся.
    #[serde(rename = "manuals", skip_serializing_if = "Option::is_none")]
    pub manuals: Option<Vec<crate::models::OfferManualDto>>,
    /// Название бренда или производителя. Должно быть записано так, как его пишет сам бренд.
    #[serde(rename = "vendor", skip_serializing_if = "Option::is_none")]
    pub vendor: Option<String>,
    /// Указывайте в виде последовательности цифр. Подойдут коды EAN-13, EAN-8, UPC-A, UPC-E или Code 128.  Для книг указывайте ISBN.  Для товаров [определенных категорий и торговых марок](https://yastatic.net/s3/doc-binary/src/support/market/ru/yandex-market-list-for-gtin.xlsx) штрихкод должен быть действительным кодом GTIN. Обратите внимание: внутренние штрихкоды, начинающиеся на 2 или 02, и коды формата Code 128 не являются GTIN.  [Что такое GTIN](*gtin)  
    #[serde(rename = "barcodes", skip_serializing_if = "Option::is_none")]
    pub barcodes: Option<Vec<String>>,
    /// Подробное описание товара: например, его преимущества и особенности.  Не давайте в описании инструкций по установке и сборке. Не используйте слова «скидка», «распродажа», «дешевый», «подарок» (кроме подарочных категорий), «бесплатно», «акция», «специальная цена», «новинка», «new», «аналог», «заказ», «хит». Не указывайте никакой контактной информации и не давайте ссылок.  Можно использовать теги:  * \\<h>, \\<h1>, \\<h2> и так далее — для заголовков; * \\<br> и \\<p> — для переноса строки; * \\<ol> — для нумерованного списка; * \\<ul> — для маркированного списка; * \\<li> — для создания элементов списка (должен находиться внутри \\<ol> или \\<ul>); * \\<div> — поддерживается, но не влияет на отображение текста.  Оптимальная длина — 400–600 символов, максимальная — 6000.  [Рекомендации и правила](https://yandex.ru/support/marketplace/assortment/fields/description.html)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Страна, где был произведен товар.  Записывайте названия стран так, как они записаны в [списке](https://yastatic.net/s3/doc-binary/src/support/market/ru/countries.xlsx).
    #[serde(
        rename = "manufacturerCountries",
        skip_serializing_if = "Option::is_none"
    )]
    pub manufacturer_countries: Option<Vec<String>>,
    #[serde(rename = "weightDimensions", skip_serializing_if = "Option::is_none")]
    pub weight_dimensions: Option<Box<crate::models::OfferWeightDimensionsDto>>,
    /// Артикул товара от производителя.
    #[serde(rename = "vendorCode", skip_serializing_if = "Option::is_none")]
    pub vendor_code: Option<String>,
    /// Метки товара, используемые магазином. Покупателям теги не видны. По тегам можно группировать и фильтровать разные товары в каталоге — например, товары одной серии, коллекции или линейки.  Максимальная длина тега 20 символов. У одного товара может быть максимум 10 тегов. Всего можно создать не больше 50 разных тегов.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "shelfLife", skip_serializing_if = "Option::is_none")]
    pub shelf_life: Option<Box<crate::models::TimePeriodDto>>,
    #[serde(rename = "lifeTime", skip_serializing_if = "Option::is_none")]
    pub life_time: Option<Box<crate::models::TimePeriodDto>>,
    #[serde(rename = "guaranteePeriod", skip_serializing_if = "Option::is_none")]
    pub guarantee_period: Option<Box<crate::models::TimePeriodDto>>,
    /// Код товара в единой Товарной номенклатуре внешнеэкономической деятельности (ТН ВЭД) — 10 или 14 цифр без пробелов.  Обязательно укажите, если он есть.
    #[serde(
        rename = "customsCommodityCode",
        skip_serializing_if = "Option::is_none"
    )]
    pub customs_commodity_code: Option<String>,
    /// Номера документов на товар: сертификата, декларации соответствия и т. п.  Передавать можно только номера документов, сканы которого загружены в кабинете продавца по [инструкции](https://yandex.ru/support/marketplace/assortment/restrictions/certificates.html).
    #[serde(rename = "certificates", skip_serializing_if = "Option::is_none")]
    pub certificates: Option<Vec<String>>,
    /// Количество грузовых мест.  Параметр используется, если товар представляет собой несколько коробок, упаковок и так далее. Например, кондиционер занимает два места — внешний и внутренний блоки в двух коробках.  Для товаров, занимающих одно место, не передавайте этот параметр.
    #[serde(rename = "boxCount", skip_serializing_if = "Option::is_none")]
    pub box_count: Option<i32>,
    #[serde(rename = "condition", skip_serializing_if = "Option::is_none")]
    pub condition: Option<Box<crate::models::OfferConditionDto>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::OfferType>,
    /// Признак цифрового товара. Укажите `true`, если товар доставляется по электронной почте.  [Как работать с цифровыми товарами](../../step-by-step/digital.md)
    #[serde(rename = "downloadable", skip_serializing_if = "Option::is_none")]
    pub downloadable: Option<bool>,
    /// Параметр включает для товара пометку 18+. Устанавливайте ее только для товаров, которые относятся к удовлетворению сексуальных потребностей.
    #[serde(rename = "adult", skip_serializing_if = "Option::is_none")]
    pub adult: Option<bool>,
    #[serde(rename = "age", skip_serializing_if = "Option::is_none")]
    pub age: Option<Box<crate::models::AgeDto>>,
    /// {% note warning \"\" %}  Этот параметр устарел. При передаче характеристик используйте `parameterValues`.  {% endnote %}  Характеристики, которые есть только у товаров конкретной категории — например, диаметр колес велосипеда или материал подошвы обуви.
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<crate::models::OfferParamDto>>,
    #[serde(rename = "basicPrice", skip_serializing_if = "Option::is_none")]
    pub basic_price: Option<Box<crate::models::GetPriceWithDiscountDto>>,
    #[serde(rename = "purchasePrice", skip_serializing_if = "Option::is_none")]
    pub purchase_price: Option<Box<crate::models::GetPriceDto>>,
    #[serde(rename = "additionalExpenses", skip_serializing_if = "Option::is_none")]
    pub additional_expenses: Option<Box<crate::models::GetPriceDto>>,
    #[serde(rename = "cofinancePrice", skip_serializing_if = "Option::is_none")]
    pub cofinance_price: Option<Box<crate::models::GetPriceDto>>,
    #[serde(rename = "cardStatus", skip_serializing_if = "Option::is_none")]
    pub card_status: Option<crate::models::OfferCardStatusType>,
    /// Список магазинов, в которых размещен товар.
    #[serde(rename = "campaigns", skip_serializing_if = "Option::is_none")]
    pub campaigns: Option<Vec<crate::models::OfferCampaignStatusDto>>,
    /// Информация о том, какие для товара доступны модели размещения.
    #[serde(rename = "sellingPrograms", skip_serializing_if = "Option::is_none")]
    pub selling_programs: Option<Vec<crate::models::OfferSellingProgramDto>>,
    /// Товар помещен в архив.
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    pub archived: Option<bool>,
}

impl GetOfferDto {
    /// Параметры товара.
    pub fn new(offer_id: String) -> GetOfferDto {
        GetOfferDto {
            offer_id,
            name: None,
            market_category_id: None,
            category: None,
            pictures: None,
            videos: None,
            manuals: None,
            vendor: None,
            barcodes: None,
            description: None,
            manufacturer_countries: None,
            weight_dimensions: None,
            vendor_code: None,
            tags: None,
            shelf_life: None,
            life_time: None,
            guarantee_period: None,
            customs_commodity_code: None,
            certificates: None,
            box_count: None,
            condition: None,
            r#type: None,
            downloadable: None,
            adult: None,
            age: None,
            params: None,
            basic_price: None,
            purchase_price: None,
            additional_expenses: None,
            cofinance_price: None,
            card_status: None,
            campaigns: None,
            selling_programs: None,
            archived: None,
        }
    }
}
