/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, Builder)]
pub struct GetOfferMappingsRequest {
    /// Идентификаторы товаров, информация о которых нужна.  {% note warning \"Такой список возвращается только целиком\" %}  Если вы запрашиваете информацию по конкретным SKU, не заполняйте: * `page_token`; * `limit`; * `cardStatuses`; * `categoryIds`; * `vendorNames`; * `tags`; * `archived`.  {% endnote %}
    #[serde(rename = "offerIds", skip_serializing_if = "Option::is_none")]
    #[builder(setter(strip_option), default)]
    pub offer_ids: Option<Vec<String>>,
    /// Фильтр по статусам карточек.  [Что такое карточка товара](https://yandex.ru/support/marketplace/assortment/content/index.html)
    #[serde(rename = "cardStatuses", skip_serializing_if = "Option::is_none")]
    #[builder(setter(strip_option), default)]
    pub card_statuses: Option<Vec<crate::models::OfferCardStatusType>>,
    /// Фильтр по категориям на Маркете.
    #[serde(rename = "categoryIds", skip_serializing_if = "Option::is_none")]
    #[builder(setter(strip_option), default)]
    pub category_ids: Option<Vec<i32>>,
    /// Фильтр по брендам.
    #[serde(rename = "vendorNames", skip_serializing_if = "Option::is_none")]
    #[builder(setter(strip_option), default)]
    pub vendor_names: Option<Vec<String>>,
    /// Фильтр по тегам.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    #[builder(setter(strip_option), default)]
    pub tags: Option<Vec<String>>,
    /// Фильтр по нахождению в архиве.  Передайте `true`, чтобы получить товары, находящиеся в архиве. Если фильтр не заполнен или передано `false`, в ответе возвращаются товары, не находящиеся в архиве.
    #[serde(rename = "archived", skip_serializing_if = "Option::is_none")]
    #[builder(setter(strip_option), default)]
    pub archived: Option<bool>,
}

impl GetOfferMappingsRequest {
    pub fn builder() -> GetOfferMappingsRequestBuilder {
        GetOfferMappingsRequestBuilder::default()
    }
}
