/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetOrdersStatsRequest : Запрос информации по заказам.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetOrdersStatsRequest {
    /// Начальная дата, когда заказ был сформирован.  Формат даты: `ГГГГ‑ММ‑ДД`.  Нельзя использовать вместе с параметрами `updateFrom` и `updateTo`.
    #[serde(rename = "dateFrom", skip_serializing_if = "Option::is_none")]
    pub date_from: Option<String>,
    /// Конечная дата, когда заказ был сформирован.  Формат даты: `ГГГГ‑ММ‑ДД`.  Нельзя использовать вместе с параметрами `updateFrom` и `updateTo`.
    #[serde(rename = "dateTo", skip_serializing_if = "Option::is_none")]
    pub date_to: Option<String>,
    /// Начальная дата периода, за который были изменения статуса заказа.  Формат даты: `ГГГГ‑ММ‑ДД`.  Нельзя использовать вместе с параметрами `dateFrom` и `dateTo`.
    #[serde(rename = "updateFrom", skip_serializing_if = "Option::is_none")]
    pub update_from: Option<String>,
    /// Конечная дата периода, за который были изменения статуса заказа.  Формат даты: `ГГГГ‑ММ‑ДД`.  Нельзя использовать вместе с параметрами `dateFrom` и `dateTo`.
    #[serde(rename = "updateTo", skip_serializing_if = "Option::is_none")]
    pub update_to: Option<String>,
    /// Список идентификаторов заказов.
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<Vec<i64>>,
    /// Список статусов заказов.
    #[serde(rename = "statuses", skip_serializing_if = "Option::is_none")]
    pub statuses: Option<Vec<crate::models::OrderStatsStatusType>>,
    /// Нужно ли вернуть только те заказы, в составе которых есть хотя бы один товар с кодом идентификации [в системе «Честный ЗНАК»](https://честныйзнак.рф/):  * `true` — да. * `false` — нет. Такие коды присваиваются товарам, которые подлежат маркировке и относятся к определенным категориям.
    #[serde(rename = "hasCis", skip_serializing_if = "Option::is_none")]
    pub has_cis: Option<bool>,
}

impl GetOrdersStatsRequest {
    /// Запрос информации по заказам.
    pub fn new() -> GetOrdersStatsRequest {
        GetOrdersStatsRequest {
            date_from: None,
            date_to: None,
            update_from: None,
            update_to: None,
            orders: None,
            statuses: None,
            has_cis: None,
        }
    }
}
