/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// GoodsStatsDto : Отчет по товарам.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GoodsStatsDto {
    /// Список товаров.
    #[serde(rename = "shopSkus", skip_serializing_if = "Option::is_none")]
    pub shop_skus: Option<Vec<crate::models::GoodsStatsGoodsDto>>,
}

impl GoodsStatsDto {
    /// Отчет по товарам.
    pub fn new() -> GoodsStatsDto {
        GoodsStatsDto { shop_skus: None }
    }
}
