/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// MaxSaleQuantumDto : Лимит на установку кванта и минимального количества товаров по категориям.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MaxSaleQuantumDto {
    /// Идентификатор категории.
    #[serde(rename = "id")]
    pub id: i64,
    /// Название категории.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Лимит на установку кванта и минимального количества товаров.
    #[serde(rename = "maxSaleQuantum", skip_serializing_if = "Option::is_none")]
    pub max_sale_quantum: Option<i32>,
}

impl MaxSaleQuantumDto {
    /// Лимит на установку кванта и минимального количества товаров по категориям.
    pub fn new(id: i64) -> MaxSaleQuantumDto {
        MaxSaleQuantumDto {
            id,
            name: None,
            max_sale_quantum: None,
        }
    }
}
