/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OfferMappingEntriesDto : Информация о товарах в каталоге.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OfferMappingEntriesDto {
    #[serde(rename = "paging", skip_serializing_if = "Option::is_none")]
    pub paging: Option<Box<crate::models::ScrollingPagerDto>>,
    /// Информация о товарах в каталоге.
    #[serde(
        rename = "offerMappingEntries",
        skip_serializing_if = "Option::is_none"
    )]
    pub offer_mapping_entries: Option<Vec<crate::models::OfferMappingEntryDto>>,
}

impl OfferMappingEntriesDto {
    /// Информация о товарах в каталоге.
    pub fn new() -> OfferMappingEntriesDto {
        OfferMappingEntriesDto {
            paging: None,
            offer_mapping_entries: None,
        }
    }
}
