/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// OfferConditionDto : Состояние уцененного товара.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OfferConditionDto {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::OfferConditionType>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<crate::models::OfferConditionQualityType>,
    /// Описание товара. Подробно опишите дефекты, насколько они заметны и где их искать.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl OfferConditionDto {
    /// Состояние уцененного товара.
    pub fn new() -> OfferConditionDto {
        OfferConditionDto {
            r#type: None,
            quality: None,
            reason: None,
        }
    }
}
