/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OfferSellingProgramStatusType : Информация о доступности или недоступности.  * `FINE` — доступно. * `REJECT` — недоступно.

/// Информация о доступности или недоступности.  * `FINE` — доступно. * `REJECT` — недоступно.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OfferSellingProgramStatusType {
    #[serde(rename = "FINE")]
    Fine,
    #[serde(rename = "REJECT")]
    Reject,
}

impl ToString for OfferSellingProgramStatusType {
    fn to_string(&self) -> String {
        match self {
            Self::Fine => String::from("FINE"),
            Self::Reject => String::from("REJECT"),
        }
    }
}

impl Default for OfferSellingProgramStatusType {
    fn default() -> OfferSellingProgramStatusType {
        Self::Fine
    }
}
