/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OfferMappingSuggestionsListDto : Список рекомендованных карточек товара.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OfferMappingSuggestionsListDto {
    /// Список товаров.
    #[serde(rename = "offers", skip_serializing_if = "Option::is_none")]
    pub offers: Option<Vec<crate::models::EnrichedMappingsOfferDto>>,
}

impl OfferMappingSuggestionsListDto {
    /// Список рекомендованных карточек товара.
    pub fn new() -> OfferMappingSuggestionsListDto {
        OfferMappingSuggestionsListDto { offers: None }
    }
}
