/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OfferCardStatusType : Статус карточки товара:  * `HAS_CARD_CAN_NOT_UPDATE` — Карточка Маркета. * `HAS_CARD_CAN_UPDATE` — Можно дополнить. * `HAS_CARD_CAN_UPDATE_ERRORS` — Изменения не приняты. * `HAS_CARD_CAN_UPDATE_PROCESSING` — Изменения на проверке. * `NO_CARD_NEED_CONTENT` — Создайте карточку. * `NO_CARD_MARKET_WILL_CREATE` — Создаст Маркет. * `NO_CARD_ERRORS` — Не создана из-за ошибки. * `NO_CARD_PROCESSING` — Проверяем данные. * `NO_CARD_ADD_TO_CAMPAIGN` — Разместите товар в магазине.  [Что обозначает каждый из статусов](https://yandex.ru/support/marketplace/assortment/content/statuses.html)

/// Статус карточки товара:  * `HAS_CARD_CAN_NOT_UPDATE` — Карточка Маркета. * `HAS_CARD_CAN_UPDATE` — Можно дополнить. * `HAS_CARD_CAN_UPDATE_ERRORS` — Изменения не приняты. * `HAS_CARD_CAN_UPDATE_PROCESSING` — Изменения на проверке. * `NO_CARD_NEED_CONTENT` — Создайте карточку. * `NO_CARD_MARKET_WILL_CREATE` — Создаст Маркет. * `NO_CARD_ERRORS` — Не создана из-за ошибки. * `NO_CARD_PROCESSING` — Проверяем данные. * `NO_CARD_ADD_TO_CAMPAIGN` — Разместите товар в магазине.  [Что обозначает каждый из статусов](https://yandex.ru/support/marketplace/assortment/content/statuses.html)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OfferCardStatusType {
    #[serde(rename = "HAS_CARD_CAN_NOT_UPDATE")]
    HasCardCanNotUpdate,
    #[serde(rename = "HAS_CARD_CAN_UPDATE")]
    HasCardCanUpdate,
    #[serde(rename = "HAS_CARD_CAN_UPDATE_ERRORS")]
    HasCardCanUpdateErrors,
    #[serde(rename = "HAS_CARD_CAN_UPDATE_PROCESSING")]
    HasCardCanUpdateProcessing,
    #[serde(rename = "NO_CARD_NEED_CONTENT")]
    NoCardNeedContent,
    #[serde(rename = "NO_CARD_MARKET_WILL_CREATE")]
    NoCardMarketWillCreate,
    #[serde(rename = "NO_CARD_ERRORS")]
    NoCardErrors,
    #[serde(rename = "NO_CARD_PROCESSING")]
    NoCardProcessing,
    #[serde(rename = "NO_CARD_ADD_TO_CAMPAIGN")]
    NoCardAddToCampaign,
}

impl ToString for OfferCardStatusType {
    fn to_string(&self) -> String {
        match self {
            Self::HasCardCanNotUpdate => String::from("HAS_CARD_CAN_NOT_UPDATE"),
            Self::HasCardCanUpdate => String::from("HAS_CARD_CAN_UPDATE"),
            Self::HasCardCanUpdateErrors => String::from("HAS_CARD_CAN_UPDATE_ERRORS"),
            Self::HasCardCanUpdateProcessing => String::from("HAS_CARD_CAN_UPDATE_PROCESSING"),
            Self::NoCardNeedContent => String::from("NO_CARD_NEED_CONTENT"),
            Self::NoCardMarketWillCreate => String::from("NO_CARD_MARKET_WILL_CREATE"),
            Self::NoCardErrors => String::from("NO_CARD_ERRORS"),
            Self::NoCardProcessing => String::from("NO_CARD_PROCESSING"),
            Self::NoCardAddToCampaign => String::from("NO_CARD_ADD_TO_CAMPAIGN"),
        }
    }
}

impl Default for OfferCardStatusType {
    fn default() -> OfferCardStatusType {
        Self::HasCardCanNotUpdate
    }
}
