/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OfferForRecommendationDto : Информация о состоянии цены на товар.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OfferForRecommendationDto {
    /// Ваш SKU — идентификатор товара в вашей системе.  Разрешена любая последовательность длиной до 255 знаков.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * SKU товара нельзя менять — можно только удалить товар и добавить заново с новым SKU.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields)
    #[serde(rename = "offerId", skip_serializing_if = "Option::is_none")]
    pub offer_id: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<Box<crate::models::BasePriceDto>>,
    #[serde(rename = "cofinancePrice", skip_serializing_if = "Option::is_none")]
    pub cofinance_price: Option<Box<crate::models::GetPriceDto>>,
    #[serde(rename = "competitiveness", skip_serializing_if = "Option::is_none")]
    pub competitiveness: Option<crate::models::PriceCompetitivenessType>,
    /// Количество показов карточки товара за последние 7 дней.
    #[serde(rename = "shows", skip_serializing_if = "Option::is_none")]
    pub shows: Option<i64>,
}

impl OfferForRecommendationDto {
    /// Информация о состоянии цены на товар.
    pub fn new() -> OfferForRecommendationDto {
        OfferForRecommendationDto {
            offer_id: None,
            price: None,
            cofinance_price: None,
            competitiveness: None,
            shows: None,
        }
    }
}
