/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OfferPriceListResponseDto : Список цен на товары.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OfferPriceListResponseDto {
    /// Страница списка.
    #[serde(rename = "offers", skip_serializing_if = "Option::is_none")]
    pub offers: Option<Vec<crate::models::OfferPriceResponseDto>>,
    #[serde(rename = "paging", skip_serializing_if = "Option::is_none")]
    pub paging: Option<Box<crate::models::ScrollingPagerDto>>,
    /// Количество всех цен магазина, измененных через API.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
}

impl OfferPriceListResponseDto {
    /// Список цен на товары.
    pub fn new() -> OfferPriceListResponseDto {
        OfferPriceListResponseDto {
            offers: None,
            paging: None,
            total: None,
        }
    }
}
