/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// OfferSellingProgramDto : Информация о том, по каким моделям можно продавать товар, а по каким нельзя.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OfferSellingProgramDto {
    #[serde(rename = "sellingProgram")]
    pub selling_program: crate::models::SellingProgramType,
    #[serde(rename = "status")]
    pub status: crate::models::OfferSellingProgramStatusType,
}

impl OfferSellingProgramDto {
    /// Информация о том, по каким моделям можно продавать товар, а по каким нельзя.
    pub fn new(
        selling_program: crate::models::SellingProgramType,
        status: crate::models::OfferSellingProgramStatusType,
    ) -> OfferSellingProgramDto {
        OfferSellingProgramDto {
            selling_program,
            status,
        }
    }
}
