/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};
use std::fmt::Display;

/// OfferConditionQualityType : Внешний вид товара:  * `PERFECT` — идеальный. * `EXCELLENT` — отличный. * `GOOD` — хороший. * `NOT_SPECIFIED` — не выбран.

/// Внешний вид товара:  * `PERFECT` — идеальный. * `EXCELLENT` — отличный. * `GOOD` — хороший. * `NOT_SPECIFIED` — не выбран.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OfferConditionQualityType {
    #[serde(rename = "PERFECT")]
    Perfect,
    #[serde(rename = "EXCELLENT")]
    Excellent,
    #[serde(rename = "GOOD")]
    Good,
    #[serde(rename = "NOT_SPECIFIED")]
    NotSpecified,
}

impl Display for OfferConditionQualityType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str = match self {
            Self::Perfect => String::from("PERFECT"),
            Self::Excellent => String::from("EXCELLENT"),
            Self::Good => String::from("GOOD"),
            Self::NotSpecified => String::from("NOT_SPECIFIED"),
        };
        write!(f, "{}", str)
    }
}

impl Default for OfferConditionQualityType {
    fn default() -> OfferConditionQualityType {
        Self::Perfect
    }
}
