/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OfferPriceResponseDto : Информация об установленной цене на товар.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OfferPriceResponseDto {
    /// Идентификатор предложения из прайс-листа.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<Box<crate::models::PriceDto>>,
    /// SKU на Маркете.
    #[serde(rename = "marketSku", skip_serializing_if = "Option::is_none")]
    pub market_sku: Option<i64>,
    /// Дата и время последнего обновления цены на товар.
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl OfferPriceResponseDto {
    /// Информация об установленной цене на товар.
    pub fn new() -> OfferPriceResponseDto {
        OfferPriceResponseDto {
            id: None,
            price: None,
            market_sku: None,
            updated_at: None,
        }
    }
}
