/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrdersStatsStockType : Тип товара:  * `DEFECT` — товар бракованный.  * `FIT` — товар надлежащего качества.

/// Тип товара:  * `DEFECT` — товар бракованный.  * `FIT` — товар надлежащего качества.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrdersStatsStockType {
    #[serde(rename = "FIT")]
    Fit,
    #[serde(rename = "FREEZE")]
    Freeze,
    #[serde(rename = "AVAILABLE")]
    Available,
    #[serde(rename = "QUARANTINE")]
    Quarantine,
    #[serde(rename = "UTILIZATION")]
    Utilization,
    #[serde(rename = "DEFECT")]
    Defect,
    #[serde(rename = "EXPIRED")]
    Expired,
}

impl ToString for OrdersStatsStockType {
    fn to_string(&self) -> String {
        match self {
            Self::Fit => String::from("FIT"),
            Self::Freeze => String::from("FREEZE"),
            Self::Available => String::from("AVAILABLE"),
            Self::Quarantine => String::from("QUARANTINE"),
            Self::Utilization => String::from("UTILIZATION"),
            Self::Defect => String::from("DEFECT"),
            Self::Expired => String::from("EXPIRED"),
        }
    }
}

impl Default for OrdersStatsStockType {
    fn default() -> OrdersStatsStockType {
        Self::Fit
    }
}
