/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderBuyerInfoDto : Информация о покупателе и его номере телефона.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderBuyerInfoDto {
    /// Идентификатор покупателя.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Фамилия покупателя.
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Имя покупателя.
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Отчество покупателя.
    #[serde(rename = "middleName", skip_serializing_if = "Option::is_none")]
    pub middle_name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::OrderBuyerType>,
    /// Подменный номер телефона покупателя. Подробнее о таких номерах читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/orders/dbs/call#fake-number).  Формат номера: `+<код_страны><код_региона><номер_телефона>`.
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

impl OrderBuyerInfoDto {
    /// Информация о покупателе и его номере телефона.
    pub fn new() -> OrderBuyerInfoDto {
        OrderBuyerInfoDto {
            id: None,
            last_name: None,
            first_name: None,
            middle_name: None,
            r#type: None,
            phone: None,
        }
    }
}
