/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrdersStatsWarehouseDto : Информация о складе, на котором хранится товар.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrdersStatsWarehouseDto {
    /// Идентификатор склада.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Название склада.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl OrdersStatsWarehouseDto {
    /// Информация о складе, на котором хранится товар.
    pub fn new() -> OrdersStatsWarehouseDto {
        OrdersStatsWarehouseDto {
            id: None,
            name: None,
        }
    }
}
