/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrdersStatsItemDto : Список товаров в заказе после возможных изменений.  В ходе обработки заказа Маркет может удалить из него единицы товаров — при проблемах на складе или по инициативе пользователя.  * Если из заказа удалены все единицы товара, его не будет в списке `items` — только в списке `initialItems`.  * Если в заказе осталась хотя бы одна единица товара, он будет и в списке `items` (с уменьшенным количеством единиц `count`), и в списке `initialItems` (с первоначальным количеством единиц `initialCount`).

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrdersStatsItemDto {
    /// Название товара.
    #[serde(rename = "offerName", skip_serializing_if = "Option::is_none")]
    pub offer_name: Option<String>,
    /// SKU на Маркете.
    #[serde(rename = "marketSku", skip_serializing_if = "Option::is_none")]
    pub market_sku: Option<i64>,
    /// Ваш SKU — идентификатор товара в вашей системе.  Разрешена любая последовательность длиной до 255 знаков.  Правила использования SKU:  * У каждого товара SKU должен быть свой.  * SKU товара нельзя менять — можно только удалить товар и добавить заново с новым SKU.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields)
    #[serde(rename = "shopSku", skip_serializing_if = "Option::is_none")]
    pub shop_sku: Option<String>,
    /// Количество единиц товара с учетом удаленных единиц.  Если из заказа удалены все единицы товара, он попадет только в список `initialItems`.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Цена или скидки на товар.
    #[serde(rename = "prices", skip_serializing_if = "Option::is_none")]
    pub prices: Option<Vec<crate::models::OrdersStatsPriceDto>>,
    #[serde(rename = "warehouse", skip_serializing_if = "Option::is_none")]
    pub warehouse: Option<Box<crate::models::OrdersStatsWarehouseDto>>,
    /// Информация об удалении товара из заказа.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<Vec<crate::models::OrdersStatsDetailsDto>>,
    /// Список кодов идентификации товара [в системе «Честный ЗНАК»](https://честныйзнак.рф/).
    #[serde(rename = "cisList", skip_serializing_if = "Option::is_none")]
    pub cis_list: Option<Vec<String>>,
    /// Первоначальное количество единиц товара.
    #[serde(rename = "initialCount", skip_serializing_if = "Option::is_none")]
    pub initial_count: Option<i32>,
    /// Списанная ставка ближайшего конкурента.  Указывается в процентах от стоимости товара и умножается на 100. Например, ставка 5% обозначается как 500.
    #[serde(rename = "bidFee", skip_serializing_if = "Option::is_none")]
    pub bid_fee: Option<i32>,
    /// Порог для скидок с Маркетом на момент оформления заказа. [Что это такое?](https://yandex.ru/support/marketplace/marketing/smart-pricing.html#sponsored-discounts)  Указан в рублях. Точность — два знака после запятой.
    #[serde(rename = "cofinanceThreshold", skip_serializing_if = "Option::is_none")]
    pub cofinance_threshold: Option<f32>,
    /// Скидка с Маркетом. [Что это такое?](https://yandex.ru/support/marketplace/marketing/smart-pricing.html#sponsored-discounts)  Указана в рублях. Точность — два знака после запятой.
    #[serde(rename = "cofinanceValue", skip_serializing_if = "Option::is_none")]
    pub cofinance_value: Option<f32>,
}

impl OrdersStatsItemDto {
    /// Список товаров в заказе после возможных изменений.  В ходе обработки заказа Маркет может удалить из него единицы товаров — при проблемах на складе или по инициативе пользователя.  * Если из заказа удалены все единицы товара, его не будет в списке `items` — только в списке `initialItems`.  * Если в заказе осталась хотя бы одна единица товара, он будет и в списке `items` (с уменьшенным количеством единиц `count`), и в списке `initialItems` (с первоначальным количеством единиц `initialCount`).
    pub fn new() -> OrdersStatsItemDto {
        OrdersStatsItemDto {
            offer_name: None,
            market_sku: None,
            shop_sku: None,
            count: None,
            prices: None,
            warehouse: None,
            details: None,
            cis_list: None,
            initial_count: None,
            bid_fee: None,
            cofinance_threshold: None,
            cofinance_value: None,
        }
    }
}
