/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderDeliveryType : Способ доставки заказа:  * `DELIVERY` — курьерская доставка.  * `PICKUP` — самовывоз.  * `POST` — почта.  * `DIGITAL` — для цифровых товаров.  * `UNKNOWN` — неизвестный тип.

/// Способ доставки заказа:  * `DELIVERY` — курьерская доставка.  * `PICKUP` — самовывоз.  * `POST` — почта.  * `DIGITAL` — для цифровых товаров.  * `UNKNOWN` — неизвестный тип.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderDeliveryType {
    #[serde(rename = "DELIVERY")]
    Delivery,
    #[serde(rename = "PICKUP")]
    Pickup,
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "DIGITAL")]
    Digital,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl ToString for OrderDeliveryType {
    fn to_string(&self) -> String {
        match self {
            Self::Delivery => String::from("DELIVERY"),
            Self::Pickup => String::from("PICKUP"),
            Self::Post => String::from("POST"),
            Self::Digital => String::from("DIGITAL"),
            Self::Unknown => String::from("UNKNOWN"),
        }
    }
}

impl Default for OrderDeliveryType {
    fn default() -> OrderDeliveryType {
        Self::Delivery
    }
}
