/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderItemsModificationRequestReasonType : Причина обновления состава заказа.

/// Причина обновления состава заказа.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderItemsModificationRequestReasonType {
    #[serde(rename = "PARTNER_REQUESTED_REMOVE")]
    PartnerRequestedRemove,
    #[serde(rename = "USER_REQUESTED_REMOVE")]
    UserRequestedRemove,
}

impl ToString for OrderItemsModificationRequestReasonType {
    fn to_string(&self) -> String {
        match self {
            Self::PartnerRequestedRemove => String::from("PARTNER_REQUESTED_REMOVE"),
            Self::UserRequestedRemove => String::from("USER_REQUESTED_REMOVE"),
        }
    }
}

impl Default for OrderItemsModificationRequestReasonType {
    fn default() -> OrderItemsModificationRequestReasonType {
        Self::PartnerRequestedRemove
    }
}
