/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderBoxLayoutPartialCountDto : Информация о части товара в коробке.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderBoxLayoutPartialCountDto {
    /// Номер части, начиная с 1.
    #[serde(rename = "current")]
    pub current: i32,
    /// На сколько всего частей разделен товар.
    #[serde(rename = "total")]
    pub total: i32,
}

impl OrderBoxLayoutPartialCountDto {
    /// Информация о части товара в коробке.
    pub fn new(current: i32, total: i32) -> OrderBoxLayoutPartialCountDto {
        OrderBoxLayoutPartialCountDto { current, total }
    }
}
