/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrdersStatsDto : Информация по заказам.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrdersStatsDto {
    /// Список заказов.
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<Vec<crate::models::OrdersStatsOrderDto>>,
    #[serde(rename = "paging", skip_serializing_if = "Option::is_none")]
    pub paging: Option<Box<crate::models::ForwardScrollingPagerDto>>,
}

impl OrdersStatsDto {
    /// Информация по заказам.
    pub fn new() -> OrdersStatsDto {
        OrdersStatsDto {
            orders: None,
            paging: None,
        }
    }
}
