/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderParcelBoxDto : Информация о грузоместе.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderParcelBoxDto {
    /// Идентификатор грузоместа.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Идентификатор грузового места в информационной системе магазина.
    #[serde(rename = "fulfilmentId", skip_serializing_if = "Option::is_none")]
    pub fulfilment_id: Option<String>,
}

impl OrderParcelBoxDto {
    /// Информация о грузоместе.
    pub fn new() -> OrderParcelBoxDto {
        OrderParcelBoxDto {
            id: None,
            fulfilment_id: None,
        }
    }
}
