/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrdersStatsPriceDto : Цена или скидки на товар.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrdersStatsPriceDto {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::OrdersStatsPriceType>,
    /// Цена или скидка на единицу товара в заказе. Указана в рублях. Точность — два знака после запятой.
    #[serde(rename = "costPerItem", skip_serializing_if = "Option::is_none")]
    pub cost_per_item: Option<f32>,
    /// Суммарная цена или скидка на все единицы товара в заказе. Указана в рублях. Точность — два знака после запятой.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<f32>,
}

impl OrdersStatsPriceDto {
    /// Цена или скидки на товар.
    pub fn new() -> OrdersStatsPriceDto {
        OrdersStatsPriceDto {
            r#type: None,
            cost_per_item: None,
            total: None,
        }
    }
}
