/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderShipmentDto : Список посылок.  В параметре может указываться несколько посылок.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderShipmentDto {
    /// Идентификатор посылки, присвоенный Маркетом.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Формат даты: `ДД-ММ-ГГГГ`.
    #[serde(rename = "shipmentDate", skip_serializing_if = "Option::is_none")]
    pub shipment_date: Option<String>,
    /// **Только для модели Экспресс**  Время, к которому магазин должен упаковать заказ и перевести его в статус `READY_TO_SHIP`. После смены статуса за заказом приедет курьер.  Поле может появиться не сразу. Запрашивайте информацию о заказе в течении 5–10 минут, пока оно не вернется.  Формат времени: 24-часовой, `ЧЧ:ММ`.  Если заказ сделан организацией, параметр не возвращается до согласования даты доставки.
    #[serde(rename = "shipmentTime", skip_serializing_if = "Option::is_none")]
    pub shipment_time: Option<String>,
    /// **Только для модели DBS**  Информация для отслеживания перемещений посылки.
    #[serde(rename = "tracks", skip_serializing_if = "Option::is_none")]
    pub tracks: Option<Vec<crate::models::OrderTrackDto>>,
    /// Список грузовых мест.
    #[serde(rename = "boxes", skip_serializing_if = "Option::is_none")]
    pub boxes: Option<Vec<crate::models::OrderParcelBoxDto>>,
}

impl OrderShipmentDto {
    /// Список посылок.  В параметре может указываться несколько посылок.
    pub fn new() -> OrderShipmentDto {
        OrderShipmentDto {
            id: None,
            shipment_date: None,
            shipment_time: None,
            tracks: None,
            boxes: None,
        }
    }
}
