/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderItemInstanceDto : Переданные вами для данной позиции коды маркировки или УИНы. Коды «Честного знака» возвращаются в двух вариантах — с криптохвостом и без.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderItemInstanceDto {
    /// Код идентификации единицы товара [в системе «Честный ЗНАК»](https://честныйзнак.рф/) без криптохвоста.
    #[serde(rename = "cis", skip_serializing_if = "Option::is_none")]
    pub cis: Option<String>,
    /// Код идентификации единицы товара [в системе «Честный ЗНАК»](https://честныйзнак.рф/) с криптохвостом.
    #[serde(rename = "cisFull", skip_serializing_if = "Option::is_none")]
    pub cis_full: Option<String>,
    /// УИН ювелирного изделия (16-значный код) Производитель получает УИН, когда регистрирует изделие в системе контроля за оборотом драгоценных металлов и камней — ГИИС ДМДК.
    #[serde(rename = "uin", skip_serializing_if = "Option::is_none")]
    pub uin: Option<String>,
    /// Регистрационный номер партии товара.  Представляет собой строку из четырех чисел, разделенных косой чертой: ХХХХХХХХ/ХХХХХХ/ХХХХХХХ/ХХХ.  Первая часть — код таможни, которая зарегистрировала декларацию на партию товара. Далее — дата, номер декларации и номер маркированного товара в декларации.
    #[serde(rename = "rnpt", skip_serializing_if = "Option::is_none")]
    pub rnpt: Option<String>,
    /// Грузовая таможенная декларация.  Представляет собой строку из трех чисел, разделенных косой чертой: ХХХХХХХХ/ХХХХХХ/ХХХХХХХ.  Первая часть — код таможни, которая зарегистрировала декларацию на ввезенные товары. Далее — дата и номер декларации.
    #[serde(rename = "gtd", skip_serializing_if = "Option::is_none")]
    pub gtd: Option<String>,
}

impl OrderItemInstanceDto {
    /// Переданные вами для данной позиции коды маркировки или УИНы. Коды «Честного знака» возвращаются в двух вариантах — с криптохвостом и без.
    pub fn new() -> OrderItemInstanceDto {
        OrderItemInstanceDto {
            cis: None,
            cis_full: None,
            uin: None,
            rnpt: None,
            gtd: None,
        }
    }
}
