/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrdersStatsOrderPaymentType : Тип оплаты заказа: - `CREDIT` — заказ оформлен в кредит. - `POSTPAID` — заказ оплачен после того, как был получен. - `PREPAID` — заказ оплачен до того, как был получен.

/// Тип оплаты заказа: - `CREDIT` — заказ оформлен в кредит. - `POSTPAID` — заказ оплачен после того, как был получен. - `PREPAID` — заказ оплачен до того, как был получен.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrdersStatsOrderPaymentType {
    #[serde(rename = "CREDIT")]
    Credit,
    #[serde(rename = "POSTPAID")]
    Postpaid,
    #[serde(rename = "PREPAID")]
    Prepaid,
    #[serde(rename = "TINKOFF_CREDIT")]
    TinkoffCredit,
}

impl ToString for OrdersStatsOrderPaymentType {
    fn to_string(&self) -> String {
        match self {
            Self::Credit => String::from("CREDIT"),
            Self::Postpaid => String::from("POSTPAID"),
            Self::Prepaid => String::from("PREPAID"),
            Self::TinkoffCredit => String::from("TINKOFF_CREDIT"),
        }
    }
}

impl Default for OrdersStatsOrderPaymentType {
    fn default() -> OrdersStatsOrderPaymentType {
        Self::Credit
    }
}
