/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderItemInstanceType : Вид маркировки товара:  * `CIS` — КИЗ, идентификатор единицы товара [в системе «Честный ЗНАК»](https://честныйзнак.рф/).  * `UIN` — УИН, уникальный идентификационный номер.  * `RNPT` — РНПТ, регистрационный номер партии товара.  * `GTD` — номер ГТД, грузовой таможенной декларации.

/// Вид маркировки товара:  * `CIS` — КИЗ, идентификатор единицы товара [в системе «Честный ЗНАК»](https://честныйзнак.рф/).  * `UIN` — УИН, уникальный идентификационный номер.  * `RNPT` — РНПТ, регистрационный номер партии товара.  * `GTD` — номер ГТД, грузовой таможенной декларации.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderItemInstanceType {
    #[serde(rename = "CIS")]
    Cis,
    #[serde(rename = "UIN")]
    Uin,
    #[serde(rename = "RNPT")]
    Rnpt,
    #[serde(rename = "GTD")]
    Gtd,
}

impl ToString for OrderItemInstanceType {
    fn to_string(&self) -> String {
        match self {
            Self::Cis => String::from("CIS"),
            Self::Uin => String::from("UIN"),
            Self::Rnpt => String::from("RNPT"),
            Self::Gtd => String::from("GTD"),
        }
    }
}

impl Default for OrderItemInstanceType {
    fn default() -> OrderItemInstanceType {
        Self::Cis
    }
}
