/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderBoxLayoutItemDto : Информация о товаре в коробке.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrderBoxLayoutItemDto {
    /// Идентификатор товара в заказе.  {% cut \"Где его взять\" %}  Идентификатор приходит в ответе на запрос [GET campaigns/{campaignId}/orders/{orderId}](../../reference/orders/getOrder.md) и в запросе Маркета [POST order/accept](../../pushapi/reference/orderAccept.md) — параметр `id` в `items`.  {% endcut %}
    #[serde(rename = "id")]
    pub id: i64,
    /// Количество единиц товара в коробке.  Используйте это поле, если в коробке поедут целые товары, не разделенные на части. Не используйте это поле одновременно с `partialCount`.
    #[serde(rename = "fullCount", skip_serializing_if = "Option::is_none")]
    pub full_count: Option<i32>,
    #[serde(rename = "partialCount", skip_serializing_if = "Option::is_none")]
    pub partial_count: Option<Box<crate::models::OrderBoxLayoutPartialCountDto>>,
    /// Переданные вами коды маркировки.
    #[serde(rename = "instances", skip_serializing_if = "Option::is_none")]
    pub instances: Option<Vec<crate::models::BriefOrderItemInstanceDto>>,
}

impl OrderBoxLayoutItemDto {
    /// Информация о товаре в коробке.
    pub fn new(id: i64) -> OrderBoxLayoutItemDto {
        OrderBoxLayoutItemDto {
            id,
            full_count: None,
            partial_count: None,
            instances: None,
        }
    }
}
