/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OutletDeliveryRuleDto : Информация об условиях доставки для данной точки продаж.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OutletDeliveryRuleDto {
    /// Минимальный срок доставки товаров в точку продаж. Указан в рабочих днях.  Минимальное значение: `0` — доставка в день заказа.  Максимальное значение: `60`.  Допустимые сроки доставки (разница между `minDeliveryDays` и `maxDeliveryDays`) зависят от региона.  Для доставки по своему региону разница не должна превышать двух дней. Например, если `minDeliveryDays` равно 1, то для `maxDeliveryDays` допускаются значения от 1 до 3.  Для доставки в другие регионы:  * Если `minDeliveryDays` до 18 дней, разница не должна превышать четырех дней. Например, если `minDeliveryDays` равно 10, то для `maxDeliveryDays` допускаются значения от 10 до 14. * Если `minDeliveryDays` больше 18 дней, разница должна быть не больше чем в два раза. Например, если `minDeliveryDays` равно 21, то для `maxDeliveryDays` допускаются значения от 21 до 42.  Обязательный параметр, если `type=\"DEPOT\"` или `type=\"MIXED\"`.  Взаимоисключающий с параметром `unspecifiedDeliveryInterval`.
    #[serde(rename = "minDeliveryDays", skip_serializing_if = "Option::is_none")]
    pub min_delivery_days: Option<i32>,
    /// Максимальный срок доставки товаров в точку продаж. Указан в рабочих днях.  Минимальное значение: `0` — доставка в день заказа.  Максимальное значение: `60`.  Допустимые сроки доставки (разница между `minDeliveryDays` и `maxDeliveryDays`) зависят от региона.  Для доставки по своему региону разница не должна превышать двух дней. Например, если `minDeliveryDays` равно 1, то для `maxDeliveryDays` допускаются значения от 1 до 3.  Для доставки в другие регионы:  * Если `minDeliveryDays` до 18 дней, разница не должна превышать четырех дней. Например, если `minDeliveryDays` равно 10, то для `maxDeliveryDays` допускаются значения от 10 до 14. * Если `minDeliveryDays` больше 18 дней, разница должна быть не больше чем в два раза. Например, если `minDeliveryDays` равно 21, то для `maxDeliveryDays` допускаются значения от 21 до 42.  Обязательный параметр, если `type=\"DEPOT\"` или `type=\"MIXED\"`.  Взаимоисключающий с параметром `unspecifiedDeliveryInterval`.
    #[serde(rename = "maxDeliveryDays", skip_serializing_if = "Option::is_none")]
    pub max_delivery_days: Option<i32>,
    /// Идентификатор службы доставки товаров в точку продаж.  Информацию о службе доставки можно получить с помощью запроса [GET delivery/services](../../reference/orders/getDeliveryServices.md).
    #[serde(rename = "deliveryServiceId", skip_serializing_if = "Option::is_none")]
    pub delivery_service_id: Option<i64>,
    /// Час, до которого покупателю нужно сделать заказ, чтобы он был доставлен в точку продаж в сроки от `minDeliveryDays` до `maxDeliveryDays`.  Если покупатель оформит заказ после указанного часа, он будет доставлен в сроки от `minDeliveryDays` + 1 рабочий день до `maxDeliveryDays` + 1 рабочий день.  Значение по умолчанию: `24`.
    #[serde(rename = "orderBefore", skip_serializing_if = "Option::is_none")]
    pub order_before: Option<i32>,
    /// Цена на товар, начиная с которой действует бесплатный самовывоз товара из точки продаж.
    #[serde(rename = "priceFreePickup", skip_serializing_if = "Option::is_none")]
    pub price_free_pickup: Option<f32>,
    /// Признак доставки товаров в точку продаж на заказ.  Признак выставлен, если:  * точный срок доставки в точку продаж заранее неизвестен (например, если магазин собирает несколько заказов для отправки в точку или населенный пункт); * все товары изготавливаются или поставляются на заказ.  Возможные значения: * `true` — товары доставляются в точку продаж на заказ.  Параметр указывается только со значением `true`.  Взаимоисключающий с параметрами `minDeliveryDays` и `maxDeliveryDays`.
    #[serde(
        rename = "unspecifiedDeliveryInterval",
        skip_serializing_if = "Option::is_none"
    )]
    pub unspecified_delivery_interval: Option<bool>,
}

impl OutletDeliveryRuleDto {
    /// Информация об условиях доставки для данной точки продаж.
    pub fn new() -> OutletDeliveryRuleDto {
        OutletDeliveryRuleDto {
            min_delivery_days: None,
            max_delivery_days: None,
            delivery_service_id: None,
            order_before: None,
            price_free_pickup: None,
            unspecified_delivery_interval: None,
        }
    }
}
