/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OutletType : Тип точки продаж.  Возможные значения:  * `DEPOT` — пункт выдачи заказов. * `MIXED` — смешанный тип точки продаж (торговый зал и пункт выдачи заказов). * `RETAIL` — розничная точка продаж (торговый зал).

/// Тип точки продаж.  Возможные значения:  * `DEPOT` — пункт выдачи заказов. * `MIXED` — смешанный тип точки продаж (торговый зал и пункт выдачи заказов). * `RETAIL` — розничная точка продаж (торговый зал).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OutletType {
    #[serde(rename = "DEPOT")]
    Depot,
    #[serde(rename = "MIXED")]
    Mixed,
    #[serde(rename = "RETAIL")]
    Retail,
    #[serde(rename = "NOT_DEFINED")]
    NotDefined,
}

impl ToString for OutletType {
    fn to_string(&self) -> String {
        match self {
            Self::Depot => String::from("DEPOT"),
            Self::Mixed => String::from("MIXED"),
            Self::Retail => String::from("RETAIL"),
            Self::NotDefined => String::from("NOT_DEFINED"),
        }
    }
}

impl Default for OutletType {
    fn default() -> OutletType {
        Self::Depot
    }
}
