/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// OutletAddressDto : Адрес точки продаж.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OutletAddressDto {
    /// Идентификатор региона.  Идентификатор можно получить c помощью запроса [GET regions](../../reference/regions/searchRegionsByName.md).  {% note alert %}  При создании и редактировании точек продаж можно указывать только регионы типов `TOWN` (город), `CITY` (крупный город) и `REPUBLIC_AREA` (район субъекта федерации). Тип региона указан в выходных параметрах type запросов [GET regions](../../reference/regions/searchRegionsByName.md) и [GET regions/{regionId}](../../reference/regions/searchRegionsById.md).  {% endnote %}
    #[serde(rename = "regionId")]
    pub region_id: i64,
    /// Улица.
    #[serde(rename = "street", skip_serializing_if = "Option::is_none")]
    pub street: Option<String>,
    /// Номер дома.
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<String>,
    /// Номер строения.
    #[serde(rename = "building", skip_serializing_if = "Option::is_none")]
    pub building: Option<String>,
    /// Номер владения.
    #[serde(rename = "estate", skip_serializing_if = "Option::is_none")]
    pub estate: Option<String>,
    /// Номер корпуса.
    #[serde(rename = "block", skip_serializing_if = "Option::is_none")]
    pub block: Option<String>,
    /// Дополнительная информация.
    #[serde(rename = "additional", skip_serializing_if = "Option::is_none")]
    pub additional: Option<String>,
    /// Порядковый номер километра дороги, на котором располагается точка продаж, если отсутствует улица.
    #[serde(rename = "km", skip_serializing_if = "Option::is_none")]
    pub km: Option<i32>,
    /// {% note warning \"\" %}  Этот параметр устарел. Не используйте его. Город или населенный пункт возвращается в параметре `regionId`.  {% endnote %}
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
}

impl OutletAddressDto {
    /// Адрес точки продаж.
    pub fn new(region_id: i64) -> OutletAddressDto {
        OutletAddressDto {
            region_id,
            street: None,
            number: None,
            building: None,
            estate: None,
            block: None,
            additional: None,
            km: None,
            city: None,
        }
    }
}
