/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// PagedReturnsDto : Возвраты.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PagedReturnsDto {
    #[serde(rename = "paging", skip_serializing_if = "Option::is_none")]
    pub paging: Option<Box<crate::models::ForwardScrollingPagerDto>>,
    /// Список возвратов.
    #[serde(rename = "returns", skip_serializing_if = "Option::is_none")]
    pub returns: Option<Vec<crate::models::ReturnDto>>,
}

impl PagedReturnsDto {
    /// Возвраты.
    pub fn new() -> PagedReturnsDto {
        PagedReturnsDto {
            paging: None,
            returns: None,
        }
    }
}
