/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// PalletsCountDto : Количество палет в отгрузке.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PalletsCountDto {
    /// Количество палет, которое заявил продавец.
    #[serde(rename = "planned", skip_serializing_if = "Option::is_none")]
    pub planned: Option<i32>,
    /// Количество палет, которое приняли в сортировочном центре.
    #[serde(rename = "fact", skip_serializing_if = "Option::is_none")]
    pub fact: Option<i32>,
}

impl PalletsCountDto {
    /// Количество палет в отгрузке.
    pub fn new() -> PalletsCountDto {
        PalletsCountDto {
            planned: None,
            fact: None,
        }
    }
}
