/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ParameterType : Тип данных:  * `TEXT` — текст. * `ENUM` — список возможных значений. * `BOOLEAN` — `true` или `false`. * `NUMERIC` — число.

/// Тип данных:  * `TEXT` — текст. * `ENUM` — список возможных значений. * `BOOLEAN` — `true` или `false`. * `NUMERIC` — число.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParameterType {
    #[serde(rename = "TEXT")]
    Text,
    #[serde(rename = "ENUM")]
    Enum,
    #[serde(rename = "BOOLEAN")]
    Boolean,
    #[serde(rename = "NUMERIC")]
    Numeric,
}

impl ToString for ParameterType {
    fn to_string(&self) -> String {
        match self {
            Self::Text => String::from("TEXT"),
            Self::Enum => String::from("ENUM"),
            Self::Boolean => String::from("BOOLEAN"),
            Self::Numeric => String::from("NUMERIC"),
        }
    }
}

impl Default for ParameterType {
    fn default() -> ParameterType {
        Self::Text
    }
}
