/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// PlacementType : Модель, по которой работает магазин:  * `FBS` — FBS или Экспресс. * `FBY` — FBY. * `DBS` — DBS.

/// Модель, по которой работает магазин:  * `FBS` — FBS или Экспресс. * `FBY` — FBY. * `DBS` — DBS.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PlacementType {
    #[serde(rename = "FBS")]
    Fbs,
    #[serde(rename = "FBY")]
    Fby,
    #[serde(rename = "DBS")]
    Dbs,
}

impl ToString for PlacementType {
    fn to_string(&self) -> String {
        match self {
            Self::Fbs => String::from("FBS"),
            Self::Fby => String::from("FBY"),
            Self::Dbs => String::from("DBS"),
        }
    }
}

impl Default for PlacementType {
    fn default() -> PlacementType {
        Self::Fbs
    }
}
