/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use std::fmt::Display;
use serde::{Deserialize, Serialize};

/// PriceQuarantineVerdictParamNameType : Имя параметра причины скрытия товара по цене.  * `CURRENT_PRICE` — цена, из-за которой товар попал в карантин. * `LAST_VALID_PRICE` — последняя цена до попадания в карантин (только для карантина типа `PRICE_CHANGE`). * `MIN_PRICE` — порог попадания в карантин (только для карантина типов `LOW_PRICE` и `LOW_PRICE_PROMO`). * `CURRENCY` — валюта.

/// Имя параметра причины скрытия товара по цене.  * `CURRENT_PRICE` — цена, из-за которой товар попал в карантин. * `LAST_VALID_PRICE` — последняя цена до попадания в карантин (только для карантина типа `PRICE_CHANGE`). * `MIN_PRICE` — порог попадания в карантин (только для карантина типов `LOW_PRICE` и `LOW_PRICE_PROMO`). * `CURRENCY` — валюта.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PriceQuarantineVerdictParamNameType {
    #[serde(rename = "CURRENT_PRICE")]
    CurrentPrice,
    #[serde(rename = "LAST_VALID_PRICE")]
    LastValidPrice,
    #[serde(rename = "MIN_PRICE")]
    MinPrice,
    #[serde(rename = "CURRENCY")]
    Currency,
}

impl Display for PriceQuarantineVerdictParamNameType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str = match self {
            Self::CurrentPrice => String::from("CURRENT_PRICE"),
            Self::LastValidPrice => String::from("LAST_VALID_PRICE"),
            Self::MinPrice => String::from("MIN_PRICE"),
            Self::Currency => String::from("CURRENCY"),
        };
        write!(f, "{}", str)
    }
}

impl Default for PriceQuarantineVerdictParamNameType {
    fn default() -> PriceQuarantineVerdictParamNameType {
        Self::CurrentPrice
    }
}
