/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

/// PriceCompetitivenessThresholdsDto : Максимальные значения цены, при которых она является привлекательной или умеренной.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PriceCompetitivenessThresholdsDto {
    #[serde(rename = "optimalPrice", skip_serializing_if = "Option::is_none")]
    pub optimal_price: Option<Box<crate::models::BasePriceDto>>,
    #[serde(rename = "averagePrice", skip_serializing_if = "Option::is_none")]
    pub average_price: Option<Box<crate::models::BasePriceDto>>,
}

impl PriceCompetitivenessThresholdsDto {
    /// Максимальные значения цены, при которых она является привлекательной или умеренной.
    pub fn new() -> PriceCompetitivenessThresholdsDto {
        PriceCompetitivenessThresholdsDto {
            optimal_price: None,
            average_price: None,
        }
    }
}
