/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// PriceSuggestDto : Тип цены.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PriceSuggestDto {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<crate::models::PriceSuggestType>,
    /// Цена в рублях.
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<f32>,
}

impl PriceSuggestDto {
    /// Тип цены.
    pub fn new() -> PriceSuggestDto {
        PriceSuggestDto {
            r#type: None,
            price: None,
        }
    }
}
