/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// PriceDto : Цена с указанием скидки, валюты и времени последнего обновления.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PriceDto {
    /// Цена на товар.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f32>,
    /// Цена на товар без скидки.  Число должно быть целым. Вы можете указать цену со скидкой от 5 до 75%.  Передавайте этот параметр при каждом обновлении цены, если предоставляете скидку на товар.
    #[serde(rename = "discountBase", skip_serializing_if = "Option::is_none")]
    pub discount_base: Option<f32>,
    #[serde(rename = "currencyId", skip_serializing_if = "Option::is_none")]
    pub currency_id: Option<crate::models::CurrencyType>,
    /// Идентификатор ставки НДС, применяемой для товара:  * `2` — 10%. * `5` — 0%. * `6` — не облагается НДС. * `7` — 20%.  Если параметр не указан, используется ставка НДС, установленная в кабинете.
    #[serde(rename = "vat", skip_serializing_if = "Option::is_none")]
    pub vat: Option<i32>,
}

impl PriceDto {
    /// Цена с указанием скидки, валюты и времени последнего обновления.
    pub fn new() -> PriceDto {
        PriceDto {
            value: None,
            discount_base: None,
            currency_id: None,
            vat: None,
        }
    }
}
