/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// PutSkuBidsRequest : description.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutSkuBidsRequest {
    /// Список товаров и ставки для продвижения, которые на них нужно установить.
    #[serde(rename = "bids")]
    pub bids: Vec<crate::models::SkuBidItemDto>,
}

impl PutSkuBidsRequest {
    /// description.
    pub fn new(bids: Vec<crate::models::SkuBidItemDto>) -> PutSkuBidsRequest {
        PutSkuBidsRequest { bids }
    }
}
