/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// QualityRatingComponentType : Составляющие индекса качества.  **Для модели DBS:** * `DBS_CANCELLATION_RATE` — доля отмененных товаров. * `DBS_LATE_DELIVERY_RATE` — доля заказов, доставленных после плановой даты.  **Для моделей FBS и Экспресс:** * `FBS_CANCELLATION_RATE` — доля отмененных товаров. * `FBS_LATE_SHIP_RATE` — доля не вовремя отгруженных заказов.  **Для модели FBY:** * `FBY_LATE_DELIVERY_RATE` — доля товаров, которые приехали на склад с опозданием. * `FBY_CANCELLATION_RATE` — доля отмененных или недоставленных товаров. * `FBY_DELIVERY_DIFF_RATE` — доля товаров, которые не прибыли вместе с поставкой или которые не приняли. * `FBY_LATE_EDITING_RATE` — доля товаров, которые поздно убрали из заявки.

/// Составляющие индекса качества.  **Для модели DBS:** * `DBS_CANCELLATION_RATE` — доля отмененных товаров. * `DBS_LATE_DELIVERY_RATE` — доля заказов, доставленных после плановой даты.  **Для моделей FBS и Экспресс:** * `FBS_CANCELLATION_RATE` — доля отмененных товаров. * `FBS_LATE_SHIP_RATE` — доля не вовремя отгруженных заказов.  **Для модели FBY:** * `FBY_LATE_DELIVERY_RATE` — доля товаров, которые приехали на склад с опозданием. * `FBY_CANCELLATION_RATE` — доля отмененных или недоставленных товаров. * `FBY_DELIVERY_DIFF_RATE` — доля товаров, которые не прибыли вместе с поставкой или которые не приняли. * `FBY_LATE_EDITING_RATE` — доля товаров, которые поздно убрали из заявки.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QualityRatingComponentType {
    #[serde(rename = "DBS_CANCELLATION_RATE")]
    DbsCancellationRate,
    #[serde(rename = "DBS_LATE_DELIVERY_RATE")]
    DbsLateDeliveryRate,
    #[serde(rename = "FBS_CANCELLATION_RATE")]
    FbsCancellationRate,
    #[serde(rename = "FBS_LATE_SHIP_RATE")]
    FbsLateShipRate,
    #[serde(rename = "FBY_LATE_DELIVERY_RATE")]
    FbyLateDeliveryRate,
    #[serde(rename = "FBY_CANCELLATION_RATE")]
    FbyCancellationRate,
    #[serde(rename = "FBY_DELIVERY_DIFF_RATE")]
    FbyDeliveryDiffRate,
    #[serde(rename = "FBY_LATE_EDITING_RATE")]
    FbyLateEditingRate,
}

impl ToString for QualityRatingComponentType {
    fn to_string(&self) -> String {
        match self {
            Self::DbsCancellationRate => String::from("DBS_CANCELLATION_RATE"),
            Self::DbsLateDeliveryRate => String::from("DBS_LATE_DELIVERY_RATE"),
            Self::FbsCancellationRate => String::from("FBS_CANCELLATION_RATE"),
            Self::FbsLateShipRate => String::from("FBS_LATE_SHIP_RATE"),
            Self::FbyLateDeliveryRate => String::from("FBY_LATE_DELIVERY_RATE"),
            Self::FbyCancellationRate => String::from("FBY_CANCELLATION_RATE"),
            Self::FbyDeliveryDiffRate => String::from("FBY_DELIVERY_DIFF_RATE"),
            Self::FbyLateEditingRate => String::from("FBY_LATE_EDITING_RATE"),
        }
    }
}

impl Default for QualityRatingComponentType {
    fn default() -> QualityRatingComponentType {
        Self::DbsCancellationRate
    }
}
