/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReportFormatType : Формат отчета:  * `FILE` — файл с электронной таблицей. * `CSV` — ZIP-архив с CSV-файлами на каждый лист отчета.

/// Формат отчета:  * `FILE` — файл с электронной таблицей. * `CSV` — ZIP-архив с CSV-файлами на каждый лист отчета.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReportFormatType {
    #[serde(rename = "FILE")]
    File,
    #[serde(rename = "CSV")]
    Csv,
}

impl ToString for ReportFormatType {
    fn to_string(&self) -> String {
        match self {
            Self::File => String::from("FILE"),
            Self::Csv => String::from("CSV"),
        }
    }
}

impl Default for ReportFormatType {
    fn default() -> ReportFormatType {
        Self::File
    }
}
