/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReturnDto : Возврат заказа.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReturnDto {
    /// Идентификатор возврата.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Номер заказа.
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
    /// Дата создания возврата клиентом.
    #[serde(rename = "creationDate", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    /// Дата обновления возврата.
    #[serde(rename = "updateDate", skip_serializing_if = "Option::is_none")]
    pub update_date: Option<String>,
    #[serde(rename = "refundStatus", skip_serializing_if = "Option::is_none")]
    pub refund_status: Option<crate::models::RefundStatusType>,
    #[serde(
        rename = "logisticPickupPoint",
        skip_serializing_if = "Option::is_none"
    )]
    pub logistic_pickup_point: Option<Box<crate::models::LogisticPickupPointDto>>,
    #[serde(
        rename = "shipmentRecipientType",
        skip_serializing_if = "Option::is_none"
    )]
    pub shipment_recipient_type: Option<crate::models::RecipientType>,
    #[serde(rename = "shipmentStatus", skip_serializing_if = "Option::is_none")]
    pub shipment_status: Option<crate::models::ReturnShipmentStatusType>,
    /// Сумма возврата.
    #[serde(rename = "refundAmount", skip_serializing_if = "Option::is_none")]
    pub refund_amount: Option<i64>,
    /// Список товаров в возврате.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ReturnItemDto>>,
    #[serde(rename = "returnType", skip_serializing_if = "Option::is_none")]
    pub return_type: Option<crate::models::ReturnType>,
    /// Используется ли опция **Быстрый возврат денег за дешевый брак**.
    #[serde(rename = "fastReturn", skip_serializing_if = "Option::is_none")]
    pub fast_return: Option<bool>,
}

impl ReturnDto {
    /// Возврат заказа.
    pub fn new() -> ReturnDto {
        ReturnDto {
            id: None,
            order_id: None,
            creation_date: None,
            update_date: None,
            refund_status: None,
            logistic_pickup_point: None,
            shipment_recipient_type: None,
            shipment_status: None,
            refund_amount: None,
            items: None,
            return_type: None,
            fast_return: None,
        }
    }
}
