/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReturnDecisionReasonType : Причины возврата:  * `BAD_QUALITY` — бракованный товар (есть недостатки).  * `DO_NOT_FIT` — товар не подошел.  * `WRONG_ITEM` — привезли не тот товар.  * `DAMAGE_DELIVERY` — товар поврежден при доставке.  * `LOYALTY_FAIL` — невозможно установить виновного в браке/пересорте.  * `CONTENT_FAIL` — ошибочное описание товара по вине Маркета.  * `UNKNOWN` — причина не известна.

/// Причины возврата:  * `BAD_QUALITY` — бракованный товар (есть недостатки).  * `DO_NOT_FIT` — товар не подошел.  * `WRONG_ITEM` — привезли не тот товар.  * `DAMAGE_DELIVERY` — товар поврежден при доставке.  * `LOYALTY_FAIL` — невозможно установить виновного в браке/пересорте.  * `CONTENT_FAIL` — ошибочное описание товара по вине Маркета.  * `UNKNOWN` — причина не известна.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReturnDecisionReasonType {
    #[serde(rename = "BAD_QUALITY")]
    BadQuality,
    #[serde(rename = "DOES_NOT_FIT")]
    DoesNotFit,
    #[serde(rename = "WRONG_ITEM")]
    WrongItem,
    #[serde(rename = "DAMAGE_DELIVERY")]
    DamageDelivery,
    #[serde(rename = "LOYALTY_FAIL")]
    LoyaltyFail,
    #[serde(rename = "CONTENT_FAIL")]
    ContentFail,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl ToString for ReturnDecisionReasonType {
    fn to_string(&self) -> String {
        match self {
            Self::BadQuality => String::from("BAD_QUALITY"),
            Self::DoesNotFit => String::from("DOES_NOT_FIT"),
            Self::WrongItem => String::from("WRONG_ITEM"),
            Self::DamageDelivery => String::from("DAMAGE_DELIVERY"),
            Self::LoyaltyFail => String::from("LOYALTY_FAIL"),
            Self::ContentFail => String::from("CONTENT_FAIL"),
            Self::Unknown => String::from("UNKNOWN"),
        }
    }
}

impl Default for ReturnDecisionReasonType {
    fn default() -> ReturnDecisionReasonType {
        Self::BadQuality
    }
}
