/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ReturnType : Тип заказа для фильтрации:  * `RETURN` — возврат.  * `UNREDEEMED` — невыкуп.  Если не указывать, в ответе будут и возвраты, и невыкупы.

/// Тип заказа для фильтрации:  * `RETURN` — возврат.  * `UNREDEEMED` — невыкуп.  Если не указывать, в ответе будут и возвраты, и невыкупы.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReturnType {
    #[serde(rename = "UNREDEEMED")]
    Unredeemed,
    #[serde(rename = "RETURN")]
    Return,
}

impl ToString for ReturnType {
    fn to_string(&self) -> String {
        match self {
            Self::Unredeemed => String::from("UNREDEEMED"),
            Self::Return => String::from("RETURN"),
        }
    }
}

impl Default for ReturnType {
    fn default() -> ReturnType {
        Self::Unredeemed
    }
}
