/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// SellingProgramType : Модель размещения:  * `FBY` — FBY. * `FBS` — FBS. * `DBS` — DBS. * `EXPRESS` — Экспресс.

/// Модель размещения:  * `FBY` — FBY. * `FBS` — FBS. * `DBS` — DBS. * `EXPRESS` — Экспресс.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SellingProgramType {
    #[serde(rename = "FBY")]
    Fby,
    #[serde(rename = "FBS")]
    Fbs,
    #[serde(rename = "DBS")]
    Dbs,
    #[serde(rename = "EXPRESS")]
    Express,
}

impl ToString for SellingProgramType {
    fn to_string(&self) -> String {
        match self {
            Self::Fby => String::from("FBY"),
            Self::Fbs => String::from("FBS"),
            Self::Dbs => String::from("DBS"),
            Self::Express => String::from("EXPRESS"),
        }
    }
}

impl Default for SellingProgramType {
    fn default() -> SellingProgramType {
        Self::Fby
    }
}
