/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// SetReturnDecisionRequest : Решения по позиции в возврате.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetReturnDecisionRequest {
    /// Идентификатор товара в возврате.
    #[serde(rename = "returnItemId")]
    pub return_item_id: i64,
    #[serde(rename = "decisionType")]
    pub decision_type: crate::models::ReturnRequestDecisionType,
    /// Комментарий к решению. Укажите:  * для `REFUND_MONEY_INCLUDING_SHIPMENT`— стоимость обратной пересылки;  * для `REPAIR` — когда вы устраните недостатки товара;  * для `DECLINE_REFUND` — причину отказа;  * для `OTHER_DECISION` — какое решение вы предлагаете.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
}

impl SetReturnDecisionRequest {
    /// Решения по позиции в возврате.
    pub fn new(
        return_item_id: i64,
        decision_type: crate::models::ReturnRequestDecisionType,
    ) -> SetReturnDecisionRequest {
        SetReturnDecisionRequest {
            return_item_id,
            decision_type,
            comment: None,
        }
    }
}
