/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SetOrderBoxLayoutRequest {
    /// Список коробок.
    #[serde(rename = "boxes")]
    pub boxes: Vec<crate::models::OrderBoxLayoutDto>,
    /// Передайте `true`, если вы собираетесь удалить часть товаров из заказа.
    #[serde(rename = "allowRemove", skip_serializing_if = "Option::is_none")]
    pub allow_remove: Option<bool>,
}

impl SetOrderBoxLayoutRequest {
    pub fn new(boxes: Vec<crate::models::OrderBoxLayoutDto>) -> SetOrderBoxLayoutRequest {
        SetOrderBoxLayoutRequest {
            boxes,
            allow_remove: None,
        }
    }
}
