/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ShelfsStatisticsAttributionType : Тип атрибуции:   * `CLICKS` — по кликам.   * `SHOWS` — по показам. <br><br>  О том, какие данные в отчете зависят и не зависят от типа атрибуции, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/marketing/shelf#stats).

/// Тип атрибуции:   * `CLICKS` — по кликам.   * `SHOWS` — по показам. <br><br>  О том, какие данные в отчете зависят и не зависят от типа атрибуции, читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/marketing/shelf#stats).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShelfsStatisticsAttributionType {
    #[serde(rename = "CLICKS")]
    Clicks,
    #[serde(rename = "SHOWS")]
    Shows,
}

impl ToString for ShelfsStatisticsAttributionType {
    fn to_string(&self) -> String {
        match self {
            Self::Clicks => String::from("CLICKS"),
            Self::Shows => String::from("SHOWS"),
        }
    }
}

impl Default for ShelfsStatisticsAttributionType {
    fn default() -> ShelfsStatisticsAttributionType {
        Self::Clicks
    }
}
