/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ShipmentInfoDtoAllOf {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<crate::models::ShipmentStatusType>,
    /// Описание статуса отгрузки.
    #[serde(rename = "statusDescription", skip_serializing_if = "Option::is_none")]
    pub status_description: Option<String>,
    /// Время последнего изменения статуса отгрузки.
    #[serde(rename = "statusUpdateTime", skip_serializing_if = "Option::is_none")]
    pub status_update_time: Option<String>,
}

impl ShipmentInfoDtoAllOf {
    pub fn new() -> ShipmentInfoDtoAllOf {
        ShipmentInfoDtoAllOf {
            status: None,
            status_description: None,
            status_update_time: None,
        }
    }
}
