/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ShipmentPalletLabelPageFormatType : Формат страницы: * `A4` — формат страницы A4. * `A8` — формат страницы A8.

/// Формат страницы: * `A4` — формат страницы A4. * `A8` — формат страницы A8.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShipmentPalletLabelPageFormatType {
    #[serde(rename = "A4")]
    A4,
    #[serde(rename = "A8")]
    A8,
}

impl ToString for ShipmentPalletLabelPageFormatType {
    fn to_string(&self) -> String {
        match self {
            Self::A4 => String::from("A4"),
            Self::A8 => String::from("A8"),
        }
    }
}

impl Default for ShipmentPalletLabelPageFormatType {
    fn default() -> ShipmentPalletLabelPageFormatType {
        Self::A4
    }
}
