/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// ShowsSalesGroupingType : Группировка данных отчета. Возможные значения: * `CATEGORIES` — группировка по категориям. * `OFFERS` — группировка по товарам.

/// Группировка данных отчета. Возможные значения: * `CATEGORIES` — группировка по категориям. * `OFFERS` — группировка по товарам.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ShowsSalesGroupingType {
    #[serde(rename = "CATEGORIES")]
    Categories,
    #[serde(rename = "OFFERS")]
    Offers,
}

impl ToString for ShowsSalesGroupingType {
    fn to_string(&self) -> String {
        match self {
            Self::Categories => String::from("CATEGORIES"),
            Self::Offers => String::from("OFFERS"),
        }
    }
}

impl Default for ShowsSalesGroupingType {
    fn default() -> ShowsSalesGroupingType {
        Self::Categories
    }
}
