/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransferOrdersFromShipmentRequest : Запрос переноса заказов из отгрузки.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransferOrdersFromShipmentRequest {
    /// Список заказов, которые вы не успеваете подготовить.
    #[serde(rename = "orderIds")]
    pub order_ids: Vec<i64>,
}

impl TransferOrdersFromShipmentRequest {
    /// Запрос переноса заказов из отгрузки.
    pub fn new(order_ids: Vec<i64>) -> TransferOrdersFromShipmentRequest {
        TransferOrdersFromShipmentRequest { order_ids }
    }
}
