/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// TurnoverDto : Информация об оборачиваемости товара.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TurnoverDto {
    #[serde(rename = "turnover")]
    pub turnover: crate::models::TurnoverType,
    /// Значение в днях. [Что это за число?](https://yandex.ru/support/marketplace/analytics/turnover.html)
    #[serde(rename = "turnoverDays", skip_serializing_if = "Option::is_none")]
    pub turnover_days: Option<f64>,
}

impl TurnoverDto {
    /// Информация об оборачиваемости товара.
    pub fn new(turnover: crate::models::TurnoverType) -> TurnoverDto {
        TurnoverDto {
            turnover,
            turnover_days: None,
        }
    }
}
