/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdatePriceWithDiscountDtoAllOf {
    /// Цена до скидки.  Число должно быть целым. Вы можете указать цену со скидкой от 5 до 75%.  Передавайте этот параметр при каждом обновлении цены, если предоставляете скидку на товар.
    #[serde(rename = "discountBase", skip_serializing_if = "Option::is_none")]
    pub discount_base: Option<f32>,
}

impl UpdatePriceWithDiscountDtoAllOf {
    pub fn new() -> UpdatePriceWithDiscountDtoAllOf {
        UpdatePriceWithDiscountDtoAllOf {
            discount_base: None,
        }
    }
}
