/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// UpdateOfferMappingDto : Информация о товаре.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateOfferMappingDto {
    #[serde(rename = "offer")]
    pub offer: Box<crate::models::UpdateOfferDto>,
    #[serde(rename = "mapping", skip_serializing_if = "Option::is_none")]
    pub mapping: Option<Box<crate::models::UpdateMappingDto>>,
}

impl UpdateOfferMappingDto {
    /// Информация о товаре.
    pub fn new(offer: crate::models::UpdateOfferDto) -> UpdateOfferMappingDto {
        UpdateOfferMappingDto {
            offer: Box::new(offer),
            mapping: None,
        }
    }
}
