/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции: * управление каталогом товаров и витриной, * обработка заказов, * изменение настроек магазина, * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */
use derive_builder::Builder;
use serde::{Deserialize, Serialize};

/// UpdateCampaignOfferDto : Параметры размещения товара в магазине.
#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, Builder)]
pub struct UpdateCampaignOfferDto {
    /// Ваш SKU — идентификатор товара в вашей системе.  Разрешена любая последовательность длиной до 255 знаков.  Правила использования SKU: * У каждого товара SKU должен быть свой.  * SKU товара нельзя менять — можно только удалить товар и добавить заново с новым SKU.  * Уже заданный SKU нельзя освободить и использовать заново для другого товара. Каждый товар должен получать новый идентификатор, до того никогда не использовавшийся в вашем каталоге.  [Что такое SKU и как его назначать](https://yandex.ru/support/marketplace/assortment/add/index.html#fields)
    #[serde(rename = "offerId")]
    #[builder(setter(into))]
    pub offer_id: String,
    #[serde(rename = "quantum", skip_serializing_if = "Option::is_none")]
    #[builder(setter(custom))]
    pub quantum: Option<Box<crate::models::QuantumDto>>,
    /// Есть ли товар в продаже.
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    #[builder(setter(strip_option))]
    pub available: Option<bool>,
    /// Ставка НДС, применяемая для товара. Задается цифрой: * `2` — 10%. * `5` — 0%. * `6` — не облагается НДС. * `7` — 20%.  Если параметр не указан, используется ставка НДС, установленная в кабинете продавца на Маркете.
    #[serde(rename = "vat", skip_serializing_if = "Option::is_none")]
    #[builder(setter(strip_option), default)]
    pub vat: Option<i32>,
}

impl UpdateCampaignOfferDto {
    /// Параметры размещения товара в магазине.
    pub fn builder() -> UpdateCampaignOfferDtoBuilder {
        UpdateCampaignOfferDtoBuilder::default()
    }
}
impl UpdateCampaignOfferDtoBuilder {
    pub fn quantum(&mut self, min_quantity: i32, quantity_step: i32) -> &mut Self {
        self.quantum = Some(Some(Box::new(crate::models::QuantumDto::new(
            min_quantity,
            quantity_step,
        ))));
        self
    }
}
