/*
 * Партнерский API Маркета
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 *
 * Generated by: https://openapi-generator.tech
 */

/// WarehouseStockType : Тип остатков товаров на складе:  * `AVAILABLE` (соответствует типу «Доступный к заказу» в отчете «Остатки на складе» в кабинете продавца на Маркете) — товар, доступный для продажи.  * `DEFECT` (соответствует типу «Брак») — товар с браком.  * `EXPIRED` (соответствует типу «Просрочен») — товар с истекшим сроком годности.  * `FIT` (соответствует типу «Годный») — товар, который доступен для продажи или уже зарезервирован.  * `FREEZE` — товар, который зарезервирован для заказов.  * `QUARANTINE` (соответствует типу «Карантин») — товар, временно недоступный для продажи (например, товар перемещают из одного помещения склада в другое).  * `UTILIZATION` — товар, который будет утилизирован.

/// Тип остатков товаров на складе:  * `AVAILABLE` (соответствует типу «Доступный к заказу» в отчете «Остатки на складе» в кабинете продавца на Маркете) — товар, доступный для продажи.  * `DEFECT` (соответствует типу «Брак») — товар с браком.  * `EXPIRED` (соответствует типу «Просрочен») — товар с истекшим сроком годности.  * `FIT` (соответствует типу «Годный») — товар, который доступен для продажи или уже зарезервирован.  * `FREEZE` — товар, который зарезервирован для заказов.  * `QUARANTINE` (соответствует типу «Карантин») — товар, временно недоступный для продажи (например, товар перемещают из одного помещения склада в другое).  * `UTILIZATION` — товар, который будет утилизирован.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WarehouseStockType {
    #[serde(rename = "FIT")]
    Fit,
    #[serde(rename = "FREEZE")]
    Freeze,
    #[serde(rename = "AVAILABLE")]
    Available,
    #[serde(rename = "QUARANTINE")]
    Quarantine,
    #[serde(rename = "UTILIZATION")]
    Utilization,
    #[serde(rename = "DEFECT")]
    Defect,
    #[serde(rename = "EXPIRED")]
    Expired,
}

impl ToString for WarehouseStockType {
    fn to_string(&self) -> String {
        match self {
            Self::Fit => String::from("FIT"),
            Self::Freeze => String::from("FREEZE"),
            Self::Available => String::from("AVAILABLE"),
            Self::Quarantine => String::from("QUARANTINE"),
            Self::Utilization => String::from("UTILIZATION"),
            Self::Defect => String::from("DEFECT"),
            Self::Expired => String::from("EXPIRED"),
        }
    }
}

impl Default for WarehouseStockType {
    fn default() -> WarehouseStockType {
        Self::Fit
    }
}
